### ISSUE TITLE
Is there any ways for one persistent storage for multiple gearman servers?

### ISSUE THREAD

**Issue by ultrakamish** [gearman/gearmand#100]
I found a few same questions, but they're outdated (for example, [this](https://groups.google.com/forum/#!topic/gearman/lBmYTanxZ5Y) is by 2011 year). But what for now?  _Can I safely have multiple gearmand servers all sharing the same persistent queue?_ Or not? I really want to use gearman in my cluster, but i don't want to lose any data and also want to process all queries even if one gearman server is down.

**Comment by SpamapS** [comment]
Yes you can in theory, but that may not be the best idea. One point of gearmand is to not share _anything_ that doesn't have to be shared.

Also, if you have a big enough cluster to need multiple gearmands, you should use a worker-storage approach. Storage workers should store foreground (not background) jobs in whatever safe/available/scalable storage works best for your system, and then re-submit them to the real workers as foreground jobs. This way you can scale gearmand separate from storage. You can see two examples here that store jobs in SQL databases:

https://github.com/SpamapS/gearstore
https://github.com/dormando/Garivini

The point of gearman and its protocol is to quickly distribute work from an arbitrary number of clients to an arbitrary number of workers efficiently. It is not the best general purpose message queue, even though background jobs feel a bit like that.

**Comment by ultrakamish** [comment]
Thank you, i got it.
