### ISSUE TITLE
Gearman jobs hold jobs of dead workers

### ISSUE THREAD

**Issue by subbiwy** [gearman/gearmand#105]
Hi, 
We are using Gearman server for running the jobs in the back ground. Gearman Clients push new jobs to the server and clients returns with out waiting for job status(for background requirment) . 

Recenly noticed that gearman is not releasing jobs of dead workers, I mean it still points to the workers of instances which are terminated. Gearman server is not realising the jobs nearly 2 hours. 

**Gearman config**:

> -d
> --round-robin
> --pid-file=/home/ftpcmbin/cm/program-data/locks/gearman/gearman.pid
> --log-file=/home/ftpcmbin/cm/program-data/logs/gearman/gearman.log
> --keepalive 
> --keepalive-idle=30 
> --keepalive-interval=10 
> --keepalive-count=6**

Our gearman config also had an entry of "keepalive-idle" with 30 seconds. It means gearman should start sending tcp probe after 30 seconds of tcp connection idle? 

We have looked into your gearam code further about these tcp keepalive timeout values, It lookes like  keepalive **opt_keepalive_idle**, **opt_keepalive_interval**, **opt_keepalive_count**, values are not getting used inside your code.

Our default system values are 
 /proc/sys/net/ipv4/tcp_keepalive_time  7200
/proc/sys/net/ipv4/tcp_keepalive_intvl  75
/proc/sys/net/ipv4/tcp_keepalive_probes  9

From our netstat o/p we can see that gearman connection tcp_keepalive_time is set to 7240. Plese check th netstat output here 

**netstat -c -anpo  | grep "10.0.2" | grep 4730 | grep 42435
tcp        0      0 10.0.1.49:4730              10.0.2.216:42435            ESTABLISHED 25760/gearmand      keepalive (6949.29/0/0)**

Are you relying on defalut system values if yes do you want us to change the default system values?

Regards
Subbi reddy

**Comment by SpamapS** [comment]
Hi! Thanks for taking the time to report your issue.

What version are you running?
If not 1.1.15, can you try it?
What OS?
Did you build it yourself?

Note this code:

https://github.com/gearman/gearmand/blob/master/libgearman-server/gearmand.cc#L528-L535

Which clearly does use the opt values. But obviously you're not seeing them used, so I wonder if there are other factors. Thanks!

**Comment by subbiwy** [comment]
Hi, 
Thanks for your help in addressing it.

What version are you running?
gearmand-1.1.7 . 


If not 1.1.15, can you try it?
We are using very old version only but this version also supports tcp_keepalive option,  Still need to move to the new versions but need to rollout to all of our modules. Have not upgraded to the latest one since the old one itself fit our requirements and it has been running since 4 years with out issue. 

What OS?
Our linux version is "Linux 3.14.20-20.44.amzn1.x86_64 x86_64"

Did you build it yourself?
**Yes**

I have attached gdb and printed socketopt values while starting gearmand  server (gdb /home/ftpcmbin/cm/programs/spider/repo/current/bin/gearmand). 

562     in libgearman-server/gearmand.cc 
**Gdb output
p gearmand->_socketopt
$1 = {_keepalive = true, _keepalive_idle = -1, _keepalive_interval = -1, _keepalive_count = -1}**

It looks like "_keepalive_idle" variable is reading from config but not setting it .
I noticed that  "**gearmand_config_sockopt_keepalive_idle**" is also not getting called from any other place in your repo 

From the gdb I can see that _keepalive_idle is -1 . 

Am I doing some thing wrong here?

**Comment by p-alik** [comment]
> It looks like "_keepalive_idle", "_keepalive_interval' variables are reading from config but not setting properly.
> From the gdb I can see that _keepalive_idle is -1 .
> 

@subbiwy, please, try PR #106

**Comment by subbiwy** [comment]
Thanks for your great help in fixing it

**Comment by tsmgeek** [comment]
@subbiwy did that PR fix your problem?
I am seeing same problem with my server on 1.1.15

**Comment by SpamapS** [comment]
Note that 1.1.16 released recently, with the issue fixed.

**Comment by SpamapS** [comment]
Closing since 1.1.16 fixes it. Please please please do re-open this one if the issue still appears in 1.1.16.
