### ISSUE TITLE
some questions in gearmand_io_set_revents function

### ISSUE THREAD

**Issue by yuzhiyuxia** [gearman/gearmand#107]
File：libgearman-server/io.cc
gearmand_error_t gearmand_io_set_revents(gearman_server_con_st *con, short revents)
{
....
  /* Remove external POLLOUT watch if we didn't ask for it. Otherwise we spin
    forever until another POLLIN state change. This is much more efficient
    than removing POLLOUT on every state change since some external polling
    mechanisms need to use a system call to change flags (like Linux epoll). */
  if (**_revents & POLLOUT_ && !(connection->events & POLLOUT) &&
      connection->universal->event_watch_fn != NULL**)
  {
    gearmand_error_t ret= connection->universal->**event_watch_fn(connection, _connection->events_,
                                                                (void *)connection->universal->event_watch_context**);
    if (gearmand_failed(ret))
    {
      gearmand_gerror_warn("event watch failed, closing connection", ret);
      _connection_close(connection);
      return ret;
    }
  }
...
}
question 1:how to understand the comment
question 2: Does revents & POLLOUT need to be bracketed?

**Comment by p-alik** [comment]
This part of code was commited 2011 [8c1edfa6](https://github.com/gearman/gearmand/commit/8c1edfa6b9833cc247c808720b5add7789d49919#diff-189e00c1fdb520c24d94b063eedc05eaR682)

I hope the author could answer you questions

**Comment by SpamapS** [comment]
@BrianAker any chance you can comment on this issue?

For me, the answer is:

(1) this looks like an attempt to make the code more efficient at handling I/O
(2) bitwise & has a higher precedence than logical &&, and thus is bound to its arguments tighter, so no, it does not need parenthesis.

**Comment by yuzhiyuxia** [comment]
Got it！Thanks！
