### ISSUE TITLE
WORK_FAIL response with '\0' at the end

### ISSUE THREAD

**Issue by loconox** [gearman/gearmand#108]
I'm using a php implementation of a gearman client and I'm facing an issue with the `WORK_FAIL` response.

When a worker throw an exception the server responds with `WORK_FAIL`. In the protocol description this response should has only one argument whish is the job handle. But in my case the job handle is followed by a `\0` (which cause an issue in my php client implementation). 

See https://github.com/bzikarsky/react-gearman/issues/7 for more details.

I see two possible options:

1. The documentation is wrong and the `WORK_FAIL` response has 2 arguments, like other `WORK_*` responses, but in this case the second argument is always empty ;
2. This is a bug in the server implementation.

Thanks.

**Comment by p-alik** [comment]
AFAIK WORK_FAIL packets could contain data.
I'll improve gearmand implementation.

**Comment by loconox** [comment]
Well, in this case, the protocol documentation is wrong. https://github.com/gearman/gearmand/blob/master/PROTOCOL#L431

**Comment by bzikarsky** [comment]
In case `WORK_FAIL` can contain data, [the docs](https://github.com/gearman/gearmand/blob/master/PROTOCOL#L436-L437) should reflect this.

**Comment by p-alik** [comment]
If protocol is incorrect, both `WORK_FAIL` and `WORK_EXCEPTION` are absolutely identical.
But in the [first protocol implementation](https://github.com/gearman/perl-Gearman-Server/blob/master/lib/Gearman/Server/Client.pm#L297) the only `WORK_EXCEPTION` allows arguments.

**Comment by SpamapS** [comment]
I believe PROTOCOL and the original Perl implementation agree. And gearmand is doing the right thing, which is, passing WORK_FAIL's _directly_ unmodified from the worker to the client. However, react-gearman is in fact doing the wrong thing:

https://github.com/bzikarsky/react-gearman/blob/master/src/Command/Binary/DefaultCommandFactory.php#L25

If my 8 years dormant rusty PHP reading is accurate,  the line above adds data to the WORK_FAIL, which is not allowed. So this is react-gearman's problem, not gearmands.

Thanks for taking the time to report it.

**Comment by bzikarsky** [comment]
This is quite ridiculous. Did you read the comment in the lines above the command-definition?

We introduced a 2nd argument exactly to work around thisissue with gearmand sending a `\0`-terminated job-handle and no data afterwards. @loconox even linked the discussion around this issue in his initial bug report: https://github.com/bzikarsky/react-gearman/issues/7. The diff can be found here: https://github.com/bzikarsky/react-gearman/commit/d83ce9dd4474760770976a596f9601f8394bfd67 -- Check the timestamp...

To the issue at hand:

The protocol definition states:

> Arguments given in the data part are separated by a NULL byte, and
the last argument is determined by the size of data after the last
NULL byte separator. All job handle arguments must not be longer than
64 bytes, including NULL terminator.

[`WORK_FAIL` is specified to only have 1 argument](https://github.com/gearman/gearmand/blob/master/PROTOCOL#L431-L437) and should therefore (see quote above) not be "delimited" with a `\0`. 

To me, this is either 

a) a bug somewhere in the Gearman-stack
b) a documentation bug in either `WORK_FAIL` or the general argument-spec

Thanks for taking the time to have another look at this.

**Comment by loconox** [comment]
Correct me if I'm wrong @SpamapS , but when you say that gearmand is passing WORK_FAIL directly to the client you meant that if the WORK_FAIL response is malformed it is due to the worker ?

**Comment by SpamapS** [comment]
Here's what gearmand does with these packets inside the server:

https://github.com/gearman/gearmand/blob/master/libgearman-server/server.cc#L846-L901

`gearmand` reads the handle as the only arg using the protocol-specified size, and copies the argument structure entirely into the packets that it sends to clients. No nulls are added. Nulls are, however, allowed, since it's a single fixed-length packet. The PROTOCOL sais it might be NULL terminated, so anything after any NULL should just be discarded.

So whatever worker sent the WORK_FAIL, they added a NULL and/or set the size wrong.

**Comment by loconox** [comment]
Right. It remains that this worker's behavior is not intuitive neither consistent with other commands.
Thanks for your help.
