### ISSUE TITLE
GEARMAN_CLIENT_NON_BLOCKING not working as expected

### ISSUE THREAD

**Issue by mhk** [gearman/gearmand#109]
Hello,
I am trying to figure the C-API out. In particular how to use `GEARMAN_CLIENT_NON_BLOCKING` in the client. I would have expected that by using `gearman_client_add_options(client, GEARMAN_CLIENT_NON_BLOCKING);`, my client does not block during the processing of the tasks and can do other things.

### Client
```
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <libgearman/gearman.h>

int main(void)
{
  gearman_client_st *client= gearman_client_create(NULL);

  gearman_return_t ret= gearman_client_add_server(client, "localhost", 0);
  if (gearman_failed(ret))
  {
    return EXIT_FAILURE;
  }

  gearman_client_add_options(client, GEARMAN_CLIENT_NON_BLOCKING);
  gearman_argument_t value= gearman_argument_make(0, 0, "Reverse Me", strlen("Reverse Me"));

  gearman_task_st *task= gearman_execute(client, 
                                         "reverse", strlen("reverse"),  // function
                                         NULL, 0,  // no unique value provided
                                         NULL, 
                                         &value, 0);

  if (task == NULL) // If gearman_execute() can return NULL on error
  {
    fprintf(stderr, "Error: %s\n", gearman_client_error(client));
    gearman_client_free(client);
    return EXIT_FAILURE;
  }

  do {
    // do other work...
  } while (gearman_task_is_running(task));

  // Make sure the task was run successfully
  if (gearman_success(gearman_task_return(task)))
  {
    // Make use of value
    gearman_result_st *result= gearman_task_result(task);
    printf("%.*s\n", (int)gearman_result_size(result), gearman_result_value(result));
  } else {
    fprintf(stderr, "Task was not successfull\n");
  }

  gearman_client_free(client);

  return EXIT_SUCCESS;
}
```
compiled with `g++ -std=c++11 reverse-client.cpp -lgearman -o reverse-client && ./reverse-client` using _gearman version 1.1.15_.

### Worker:
```
$ gearman -w -f reverse -- rev
```

### Expected result:
```
eM esreveR
```

### Actual result:
```
Task was not successfull
```

**Comment by p-alik** [comment]
I never used `GEARMAN_CLIENT_NON_BLOCKING` before but AFAIK [gearman](https://github.com/gearman/gearmand/blob/master/bin/gearman.cc) cli works fine with background jobs. If it's an option to you take a look in
[gearman_client_do_background](https://github.com/gearman/gearmand/blob/master/libgearman/client.cc#L768) implementation.
Meanwhile I'll test `GEARMAN_CLIENT_NON_BLOCKING` option.

**Comment by mhk** [comment]
The disadvantage of using  [`gearman_client_do_background`](https://github.com/gearman/gearmand/blob/master/libgearman/client.cc#L768) (as I am understanding it), would be that there is no back channel to the client to receive the worker produced data.

**Comment by p-alik** [comment]
Indeed, it is.

**Comment by p-alik** [comment]
For non_blocking jobs [gearman_execute](https://github.com/gearman/gearmand/blob/1.1.15/libgearman/client.cc#L1691) does not call [gearman_wait](https://github.com/gearman/gearmand/blob/1.1.15/libgearman/universal.cc#L263) and does not deliver the job to the job server.
`return gearman_gerror(client->universal, GEARMAN_IO_WAIT)` is the reason for "Task was not successful".
It looks like for non blocking jobs you have to implement something like [gearman_wait](https://github.com/gearman/gearmand/blob/1.1.15/libgearman/universal.cc#L263) by yourself.
