### ISSUE TITLE
gearmand logs UTC timestamp

### ISSUE THREAD

**Issue by p-alik** [gearman/gearmand#123]
[gearman_log](https://github.com/gearman/gearmand/blob/master/libgearman-server/log.cc#L172) sets timestamp in the logging message by `gmtime_r`. 

Here [man page](https://linux.die.net/man/3/localtime_r) excerpts to `gmtime` and `localtime`:
> The **gmtime()** function converts the calendar time timep to broken-down time representation, expressed in Coordinated Universal Time (UTC).

> The **localtime()** function converts the calendar time timep to broken-down time representation, expressed relative to the user's specified timezone.

It would be wise to switch to `localtime_r` to see log messages with usual local system timestamps.

**Comment by esabol** [comment]
I think this issue can be closed now?

**Comment by p-alik** [comment]
Done. See #124
