### ISSUE TITLE
GEARMAN_TIMEOUT error

### ISSUE THREAD

**Issue by lkebin** [gearman/gearmand#130]
Hello, the Gearman client got error:

```
GearmanClient::doBackground():
gearman_wait(GEARMAN_TIMEOUT) timeout reached, 1 servers were poll(),
no servers were available, pipe:false -> libgearman/universal.cc:337
```

Client side has setTimeout(1000 * 2). 

I checked job server and worker, everything is fine. no error/warning log at that time.

How to find out the reason of this error ?

**Comment by BrianAker** [comment]
If you don’t want a timeout then don’t set one. The “pipe: false” should mean that the connection was still up and running just fine.

The client did what it was suppose to do, it timed out.

	— Brian

**Comment by lkebin** [comment]
Hi @Brian Aker ,

As my understanding, the setTimeout will affect the sync job. like
doNormal. But doBackground should be aways work with setTimeout value.
Or my understanding is wrong ?

In my case, the client side setTimeout is global for GearmanClient object.
The client will invoke some doNormal and doBackground operations in the
same progress.

**Comment by SpamapS** [comment]
The timeout is for the _connection_, not the _job_. If you have done nothing with the connection, it will time out. As @BrianAker says... if this is not suitable, do not set a connection level timeout.

I'm going to close this. I don't think it's a bug, and the API docs are relatively clear on libgearman. The PHP may not be explaining it right (I assume that's what you're using) but that would be an issue to take up with its maintainers.

If you feel there's something we've missed, please don't hesitate to reopen this issue or open a new one. Thanks for taking the time to report here.

**Comment by lkebin** [comment]
@SpamapS 

There is my test code. The code running without timeout beyond 20 seconds.

```
<?php
$gearmanClient = new GearmanClient();
$gearmanClient->addServers('10.0.21.71:4730');
$gearmanClient->setTimeout(1000 * 20);
$time = time();
while(true){
    echo (time() - $time) . "s\n";
    $gearmanClient->doBackground('updateDataCache', 'hello world');
    sleep(1);
}
```

Results:
```
[test@localhost ~]$ php ./doBackground.php
0s
1s
2s
3s
4s
5s
6s
7s
8s
9s
10s
11s
12s
13s
14s
15s
16s
17s
18s
19s
20s
21s
22s
23s
24s
25s
^C
```

When I setup `setTimeout(1 /*milliseconds*/)` will occurs timeout.

My understanding that the connection is build in `addServers()` function, and it is persistent while  all the `while(true)`. If the timeout is for *connection*, I think the progress should be timeout after 20s, right ?

**Comment by lkebin** [comment]
@SpamapS 

I have write a client in C language to verify timeout value is for *connection* not job. 

`cat doBackground.c`

```
#include <stdio.h>
#include <unistd.h>
#include <string.h>

#include <libgearman/gearman.h>

int main(int argc, const char *argv[])
{
    char *unique = NULL;

    gearman_client_st *client= gearman_client_create(NULL);
    gearman_return_t ret= gearman_client_add_server(client, "10.0.11.11", 4730);
    if (gearman_failed(ret))
    {
        return EXIT_FAILURE;
    }

    //set timeout value 20 seconds.
    gearman_client_set_timeout(client, (1000 * 20));
    printf("%d\n", gearman_client_timeout(client));

    gearman_job_handle_t job_handle;
    for(int i = 0; i<3; i++) {
        printf("%d\n", i);
        gearman_return_t rc= gearman_client_do_background(client,
                "gid",
                (char *)unique,
                "hello world",
                strlen("hello world"),
                job_handle);

        if (gearman_success(rc)) {
            // Make use of value
        }

       // Sleep 10s for each loop
        sleep(10);
    }

    gearman_client_free(client);
    return 0;
}
```

```
cc -std=gnu99 -Wall -lgearman -o doBackground doBackground.c
```

The code work without timeout error.

**Comment by SpamapS** [comment]
Hey thanks for continuing to look at this.

Your test code proves my point. The timeout is for inactivity. It is implemented as a timeout for the underlying 'poll' call:

https://github.com/gearman/gearmand/blob/master/libgearman/universal.cc#L313-L340

Any time you submit a job, you get some activity.

**Comment by lkebin** [comment]
If I don't set *timeout* value, when the worker crashed, client (e.g.: doNormal) will aways waiting for worker.

The *timeout* error occurs at sometime, not each times. Is that job server load to high ? 

I will do more testing for reproduce the TIMEOUT error.

Thanks @SpamapS and @BrianAker  !
