### ISSUE TITLE
Travis builds fail on trusty environment

### ISSUE THREAD

**Issue by SpamapS** [gearman/gearmand#132]
https://travis-ci.org/gearman/gearmand/builds/256850426?utm_source=github_status&utm_medium=notification

We should fix whatever is causing this quickly. If we can't, we may have to assert precise while we debug. I hope to have time to investigate this week.

**Comment by p-alik** [comment]
I'm on it already.

**Comment by SpamapS** [comment]
Thanks! I'd like to do a release once this is fixed.
