### ISSUE TITLE
missing-call-to-setgroups-before-setuid /usr/sbin/gearmand

### ISSUE THREAD

**Issue by cheese** [gearman/gearmand#137]
gearmand-1.1.17

rpmlint shows this error:
gearmand.x86_64: E: missing-call-to-setgroups-before-setuid /usr/sbin/gearmand

missing-call-to-setgroups-before-setuid:
This executable is calling setuid and setgid without setgroups or initgroups.
There is a high probability this means it didn't relinquish all groups, and
this would be a potential security issue to be fixed. Seek POS36-C on the web
for details about the problem.

**Comment by SpamapS** [comment]
Seems legit. I'll look into this if I can find some time.

**Comment by esabol** [comment]
Something like:
```
    int saved_errno = errno;
    setgroups(0, NULL);
    errno = saved_errno;
```
inserted prior to https://github.com/gearman/gearmand/blob/2ff2de18c279c09f5a71b2d5766b1d295335d315/gearmand/gearmand.cc#L507
?

**Comment by esabol** [comment]
This issue can be closed if someone can confirm that rpmlint no longer complains. :)

**Comment by cheese** [comment]
OK. I tested the patch and rpmlint no longer complains.

**Comment by esabol** [comment]
Thanks for testing, @cheese !

Did rpmlint have any other complaints?

**Comment by cheese** [comment]
No. Nothing upstream should care.

**Comment by p-alik** [comment]
Thanks for testing, @cheese, one more time!
