### ISSUE TITLE
make on mac error

### ISSUE THREAD

**Issue by xming4321** [gearman/gearmand#147]
./libgearman/byteorder.h:49:10: error: expected ')'
uint64_t htonll(uint64_t);
         ^
/usr/include/sys/_endian.h:141:25: note: expanded from macro 'htonll'
#define htonll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/usr/include/libkern/_OSByteOrder.h:78:30: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
                             ^
./libgearman/byteorder.h:49:10: note: to match this '('
/usr/include/sys/_endian.h:141:25: note: expanded from macro 'htonll'
#define htonll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/usr/include/libkern/_OSByteOrder.h:78:5: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
    ^
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
                             ^
./libgearman/byteorder.h:46:10: note: to match thisIn file included from libgearman/actions.cc:39:
In file included from ./libgearman/common.h:64:
./libgearman/byteorder.h:46:10: error: expected ')'
uint64_t ntohll(uint64_t);
         ^
/usr/include/sys/_endian.h:140:25: note: expanded from macro 'ntohll'
#define ntohll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/usr/include/libkern/_OSByteOrder.h:78:30: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
                             ^
./libgearman/byteorder.h:46:10: note: to match this '('
/usr/include/sys/_endian.h:140:25: note: expanded from macro 'ntohll'
#define ntohll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/usr/include/libkern/_OSByteOrder.h:78:5: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
    ^
In file included from libgearman/actions.cc:39:
In file included from ./libgearman/common.h:64:
./libgearman/byteorder.h:49:10: error: expected ')'
uint64_t htonll(uint64_t);
         ^
/usr/include/sys/_endian.h:141: '('
/usr/include/sys/_endian.h:140:25: note: expanded from macro 'ntohll'
#define ntohll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/usr/include/libkern/_OSByteOrder.h:78:5: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
    ^
In file included from 25libgearman/allocator.cc:38:
In file included from ./libgearman/common.h:64:
./libgearman/byteorder.h:49:10: error: expected ')'
uint64_t htonll(uint64_t);
         ^
/usr/include/sys/_endian.h:141:25: note: expanded from macro 'htonll'
#define htonll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/usr/include/libkern/_OSByteOrder.h:78:30: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
                             ^
./libgearman/byteorder.h:49:10: note: to match this '('
/usr/include/sys/_endian.h:141:25: note: expanded from macro 'htonll'
#define htonll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/usr/include/libkern/_OSByteOrder.h:78:5: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
    ^
: note: expanded from macro 'htonll'
#define htonll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/usr/include/libkern/_OSByteOrder.h:78:30: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
                             ^
./libgearman/byteorder.h:49:10: note: to match this '('
/usr/include/sys/_endian.h:141:25: note: expanded from macro 'htonll'
#define htonll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/usr/include/libkern/_OSByteOrder.h:78:5: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
    ^
2 errors generated.
2 errors generated.
make[2]: *** [libgearman/libgearman_libgearman_la-argument.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [libgearman/libgearman_libgearman_la-allocator.lo] Error 1
2 errors generated.
2 errors generated.
make[2]: *** [libgearman/libgearman_libgearman_la-actions.lo] Error 1
make[2]: *** [libgearman/libgearman_libgearman_la-aggregator.lo] Error 1
2 errors generated.
make[2]: *** [libgearman/libgearman_libgearman_la-check.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by esabol** [comment]
We already have an issue for this: issue #73. There's also a work-in-progress PR for it. I recommend that you close this issue and monitor issue #73 for updates. Thanks!

**Comment by xming4321** [comment]
- [ ]
