### ISSUE TITLE
How can I get a detail documents for worker function in C/C++ ?

### ISSUE THREAD

**Issue by lkebin** [gearman/gearmand#152]
Hello, 

I'm try to write worker in C/C++ base on libgearman. Any detail documents for [gearman_worker_add_function](http://gearman.info/libgearman/gearman_worker_add_function.html) ?
I mean how to create callback function ? How to return data to client ?

Thanks.

**Comment by esabol** [comment]
Have you looked at the sample code?

https://github.com/gearman/gearmand/blob/4761b20023c0adf9c4704fc81bce6c70446857b6/examples/wc_worker.cc

**Comment by lkebin** [comment]
@esabol Thanks.

So, any data need to be return to client, just do return the data pointer into callback function, right ?
