### ISSUE TITLE
buid with hiredis error

### ISSUE THREAD

**Issue by ideamean** [gearman/gearmand#154]
I make with gcc:
gcc (GCC) 4.8.2 20131212 (Red Hat 4.8.2-8)
Copyright © 2013 Free Software Foundation, Inc.

make error as:
/usr/bin/ld: bin/gearadmin: undefined reference to symbol '__pthread_key_create@@GLIBC_2.2.5'
/usr/bin/ld: note: '__pthread_key_create@@GLIBC_2.2.5' is defined in DSO /lib64/libpthread.so.0 so try adding it to the linker command line
/lib64/libpthread.so.0: could not read symbols: Invalid operation
collect2: error: ld returned 1 exit status

**Comment by esabol** [comment]
Please provide additional information on platform, OS distribution, etc. gcc 4.8.2 is pretty old....

**Comment by ideamean** [comment]
LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch
Distributor ID:	CentOS
Description:	CentOS release 6.9 (Final)
Release:	6.9
Codename:	Final

**Comment by esabol** [comment]
Yeah, there have been reports that it won't compile on RHEL/CentOS 6.x before. There's no known solution, unfortunately. 

It compiles fine on CentOS 7.x will though, speaking from personal experience. You might want to consider upgrading.

**Comment by ideamean** [comment]
ok, tks, hope you repair it and support it on centos 6.x version.

**Comment by esabol** [comment]
The linking error with pthread_key_create is due to a bug in the binutils on whatever version of CentOS 6 this was being compiled on. The solution is to upgrade binutils. See here:

https://bugzilla.redhat.com/show_bug.cgi?id=918003

**Comment by esabol** [comment]
I recommend closing this issue.
