### ISSUE TITLE
gearmand: character conversion failed

### ISSUE THREAD

**Issue by AJMstr** [gearman/gearmand#167]
The same error occurred on multiple machine（centos 7）

[root@izbp14b6ja4jobl4bt1sfoz ~]# gearmand -d
gearmand: character conversion failed

**Comment by esabol** [comment]
I use gearmand on CentOS 7.x all the time and have never seen that. Googling revealed the following relevant links:

https://stackoverflow.com/questions/35382902/boost-program-options-throws-character-conversion-failed
https://svn.boost.org/trac/boost/ticket/11905

**Comment by AJMstr** [comment]
thx
