### ISSUE TITLE
Priority ordering is applied only per function

### ISSUE THREAD

**Issue by njam** [gearman/gearmand#173]
I was expecting that *high* prio jobs would always get executed before any *low* prio jobs, regardless of what funtion they execute. But that seems not to be the case, rather execution depends on the order that the functions were registered!

---

Let's say there are two functions: `fn_a` and `fn_b`.

If I register them in the order `fn_a`, then `fn_b`, and then queue the following jobs:
1. fn_a with prio=high
2. fn_a with prio=high
3. fn_b with prio=low
4. fn_b with prio=low

Then my worker retrieves the jobs with `GEARMAN_GRAB_JOB_ALL` in the following expected order:
1. fn_a with prio=high
2. fn_a with prio=high
3. fn_b with prio=low
4. fn_b with prio=low

But if I register the functions in the order `fn_b`, then `fn_a`, and then queue the same jobs in the same order as above, the worker receives the jobs in this order:
1. fn_b with prio=low
2. fn_b with prio=low
3. fn_a with prio=high
4. fn_a with prio=high

Low prio jobs are executed before high prio jobs, because function `fn_b` was registered before `fn_a`.

---

I'm not well informed about how Gearmand works internally. Peeking at the code I believe the function [`gearman_server_job_take()`](https://github.com/gearman/gearmand/blob/e2d76cf631414964decc2f22006a666e1c0e2424/libgearman-server/gearmand_con.cc#L360) might be causing this. It first iterates over functions, and then over priorities, and returns the first match.

**Comment by njam** [comment]
I thought it might be a feature :D Quite an irritating one though.
Thanks for looking into my question!

**Comment by SpamapS** [comment]
note that you can pass `--round-robin` to gearmand and it will ensure that your clients serve each queue equally.

**Comment by njam** [comment]
@SpamapS thanks for the hint!
The execution order with `--round-robin` is:
1. fn_b with prio=low
2. fn_a with prio=high
3. fn_b with prio=low
4. fn_a with prio=high

**Comment by esabol** [comment]
Note that job priority allocation was changed to be global in PR #431, and this will be the default behavior in gearmand version 2.0.0.

Also, `--round-robin` was made the default in PR #432. Also takes effect in the upcoming gearmand 2.0.0.
