### ISSUE TITLE
./configure file missing from 1.1.13

### ISSUE THREAD

**Issue by flavio** [gearman/gearmand#18]
The `./configure` file and the `build-aux` directories are missing from the 1.1.13 release.

Running the `./bootstrap.sh autoreconf` won't work when the directory is not a git checkout (which is the case when building the openSUSE package).

Would it be possible to re-add these files?

**Comment by SpamapS** [comment]
Hi flavio.

Good point. Those tarballs just aren't enough.

For now, if you do a 'make dist' in the git tree with 1.1.13 checked out, and it will produce a gearmand-1.1.13.tar.gz with a working configure script, that should work for your package builds. I'll see if I can add generated and signed tarballs to the release notification.

**Comment by SpamapS** [comment]
The tarballs are up now. Please give them a try and let me know.

**Comment by flavio** [comment]
Yes, that helps. Thanks a lot.
