### ISSUE TITLE
autoconf-archive does not provide ac_cxx_compile_stdcxx_0x.m4 anymore

### ISSUE THREAD

**Issue by p-alik** [gearman/gearmand#185]
According to [this commit](http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=commit;h=3ea011f8cd6c4c47bdd8e9779169efe2ad05caa6) `ac_cxx_compile_stdcxx_0x.m4` was renamed to `ax_cxx_compile_stdcxx_0x.m4`.

- https://www.gnu.org/software/autoconf-archive/ax_cxx_compile_stdcxx_0x.html
- [ax_cxx_compile_stdcxx_0x.m4 history in autoconf-archive repository](http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=history;f=m4/ax_cxx_compile_stdcxx_0x.m4)

**Comment by esabol** [comment]
> According to [this commit](http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=commit;h=3ea011f8cd6c4c47bdd8e9779169efe2ad05caa6) `ax_cxx_compile_stdcxx_0x.m4` was renamed to `ax_cxx_compile_stdcxx_0x.m4`.

Typo. One of those should be `ac_*`, presumably.

Anyway, looks good!

**Comment by p-alik** [comment]
> Typo. One of those should be ac_*, presumably.

Thank you. It's corrected.

**Comment by p-alik** [comment]
It seem's `ax_cxx_compile_stdcxx_0x.m4` is obsolete at all:
```bash
git grep AC_CXX_COMPILE_STDCXX_0X
m4/ax_cxx_compile_stdcxx_0x.m4:#   AC_CXX_COMPILE_STDCXX_0X
m4/ax_cxx_compile_stdcxx_0x.m4:AC_DEFUN([AC_CXX_COMPILE_STDCXX_0X], [
m4/pandora_check_cxx_standard.m4:  dnl AC_REQUIRE([AC_CXX_COMPILE_STDCXX_0X])
```
`pandora_check_cxx_standard.m4` also:
```bash
git grep PANDORA_CHECK_CXX_STANDARD
m4/pandora_check_cxx_standard.m4:AC_DEFUN([PANDORA_CHECK_CXX_STANDARD],[
```

Building of `gearmand` on Ubuntu 16.04 succeeds without both of them:
```bash
rm -f m4/ax_cxx_compile_stdcxx_0x.m4 m4/pandora_check_cxx_standard.m4
./configure
make
```
Should this m4 files be removed?

**Comment by esabol** [comment]
> Should this m4 files be removed?

Does it harm anything to leave them in?

**Comment by p-alik** [comment]
> Does it harm anything to leave them in?

Indeed, no. But on the other hand removed files remains in the git history and could be restored on demand.

**Comment by esabol** [comment]
This issue can be closed, right?

**Comment by p-alik** [comment]
Yes, indeed.
