### ISSUE TITLE
Travis CI tests with g++-6

### ISSUE THREAD

**Issue by p-alik** [gearman/gearmand#188]
regarding to https://docs.travis-ci.com/user/languages/cpp/#gcc-on-linux 6 and 7 could be used meanwhile for testing purpose also.

**Comment by p-alik** [comment]
builds with g++{6,7} fail
https://travis-ci.org/p-alik/gearmand/builds/450877641

**Comment by esabol** [comment]
Yes, we need this!

**Comment by p-alik** [comment]
https://github.com/p-alik/gearmand/commit/9047628a51c328fee80553c5fcca7cc6f25937c1 solves the issue for `g++6`. I would provide a PR only for `g++6` yet because `g++7` build dies on `-Werror=implicit-fallthrough=` https://travis-ci.org/p-alik/gearmand/builds/451308696.

**Comment by p-alik** [comment]
solved in #191
