### ISSUE TITLE
Travis CI tests with g++ > v6

### ISSUE THREAD

**Issue by p-alik** [gearman/gearmand#192]
An attempt to run Travis CI tests with `g++-7` failed. See https://github.com/gearman/gearmand/issues/188#issuecomment-435891565.

**Comment by p-alik** [comment]
it's done for `g++-7` in #193

**Comment by esabol** [comment]
`t/memcached` failing? 
https://travis-ci.org/gearman/gearmand

**Comment by esabol** [comment]
> > t/memcached failing?
> 
> it's fine after restart

Flaky tests are very annoying! It is hard to know when there is an actual problem or not.

**Comment by p-alik** [comment]
Unfortunately it isn't reproducible in my testing environment.
Not sure `./configure --disable-libmemcached` in [.travis.yml](https://github.com/gearman/gearmand/blob/3c35e0d7d5b60d9492d950b22ef710a499232fd9/.travis.yml#L60) is an option.

**Comment by p-alik** [comment]
Local tests are always failing in this snippet  https://github.com/gearman/gearmand/blob/c343b3b93e057dccf2a93a8109663437ceded148/libtest/signal.cc#L228-L232

**Comment by esabol** [comment]
That's EINVAL, right? According to the man page, that means 'name consists of just "/", followed by no other characters,' which doesn't seem believable. Maybe adding some more information to the error message is needed, like `lock_name` and the actual `errno` value.

**Comment by p-alik** [comment]
I beg your pardon and I have to withdraw my statement. My changes on `lock_name` cause the issue.

**Comment by p-alik** [comment]
https://api.travis-ci.org/v3/job/458552968/log.txt shows
```
libtest/client.cc:268: in start() pid(30732) localhost:46220 ping(libtest/client.cc:268: Connection refused), additionally pid: 30796 is alive: true waited: 17 server started. exec: /home/travis/build/p-alik/gearmand/libtool --mode=execute /home/travis/build/p-alik/gearmand/./gearmand/gearmand --verbose=INFO --log-file=var/log/gearmand.logpcsEGr --pid-file=var/run/gearmand.pidCbEK24 --port=46220 --queue-type=libmemcached --libmemcached-servers=localhost:57005 --listen=localhost  stderr:

tests/memcached_test.cc:119: in lp_1054377_TEST() pid(30732) Assertion 'server_startup(servers, "gearmand", first_port, argv)'
memcached.queue restart.lp:1054377					[ failed ]
```

**Comment by esabol** [comment]
If the testing code is waiting for the server to startup, maybe it just needs to wait a second before trying or retry a few times with a short delay in between attempts?

**Comment by p-alik** [comment]
As long as `gearmand` supports a queue backend, we have to test it also.

**Comment by esabol** [comment]
The fail rate seems more like 10% to me, fwiw. That's not based on any actual data, of course, just my gut.
