### ISSUE TITLE
why -Wimplicit-fallthrough breaks compilation with gcc 7?

### ISSUE THREAD

**Issue by p-alik** [gearman/gearmand#198]
Some diagnostic `pragma GCC diagnostic warning "-Wimplicit-fallthrough"` were added in #193 https://github.com/gearman/gearmand/pull/193/commits/585a04ec358449f9b6040ef1439993fe70bfa0cb for sake of `g++7`.
What caused the warnings?

**Comment by esabol** [comment]
You misspelled "breaks" in the issue title.

**Comment by esabol** [comment]
I haven't checked every single occurrence in the gearmand code yet, but I feel most (if not all) of these warnings/errors are spurious. Barring an actual bug I haven't found yet, the code was intentionally written that way, and it works as designed. The gcc developers decided this technique was a common coding error, however, and decided to warn programmers using it. Then, they made the warnings into errors.
