### ISSUE TITLE
Dist tarballs do not include any docs

### ISSUE THREAD

**Issue by oerdnj** [gearman/gearmand#21]
Hey,

your `.gitignore` contains:
```
Makefile
```
instead of
```
/Makefile
```
and thus `/docs/Makefile` gets killed when doing release tarball.

**Comment by oerdnj** [comment]
Or maybe the reason for missing `docs/Makefile` is #11, but the .gitignore is still wrong.

**Comment by SpamapS** [comment]
No I think the missing docs/Makefile is just an oversight. It is not a generated file, so it should definitely not be part of .gitignore, but I think there _are_ generated Makefiles in other dirs. Since this one is already added, .gitignore won't come into play though.

**Comment by oerdnj** [comment]
Then the district tar ball is also missing most of the `docs/source`.

**Comment by SpamapS** [comment]
@oerdnj it would be most useful if you could take a look at the PR I put up and maybe even test that './bootstrap.sh && make dist' produces a tarball that does include what you think should be there. I just reworked it to include most of docs/source. I will also be submitting a second PR which changes the stated license for docs/source to cc-by-sa 4.0.
