### ISSUE TITLE
Logging bug?

### ISSUE THREAD

**Issue by esabol** [gearman/gearmand#235]
Is `errno` missing from the list of arguments to `gearmand_log_info()` here or am I just being dumb and missing something in the implementation of `gearmand_log()`?

https://github.com/gearman/gearmand/blob/260993fc84fa26805d37895d9a9c81b0bc19092d/libgearman-server/io.cc#L169

Just to be clear, I think this line should be:
```C
            gearmand_log_info(GEARMAN_DEFAULT_LOG_PARAM, "SSL failure(%s) errno:%d", errorString, errno);
```

**Comment by SpamapS** [comment]
Yes, it looks like it is missing. Because the implementation uses vsnprintf I believe it just stops adding to the string and thus leaves errno out.

**Comment by esabol** [comment]
My log files clearly show a number there though (using 1.1.18).
