### ISSUE TITLE
Update Travis CI builds to use Ubuntu Xenial?

### ISSUE THREAD

**Issue by esabol** [gearman/gearmand#238]
https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment says:

> Since Ubuntu 14.04 reaches End of Life on April 30th, 2019, we’ll be gradually setting the default distribution for builds to Linux, Ubuntu Xenial 16.04.

Should we update gearmand's `.travis.yml` to use Xenial to keep pace?

**Comment by p-alik** [comment]
gcc-4.9 build doesn't work on xenial
https://travis-ci.org/p-alik/gearmand/jobs/526389084#L2249-L2277

**Comment by esabol** [comment]
> gcc-4.9 build doesn't work on xenial
> https://travis-ci.org/p-alik/gearmand/jobs/526389084#L2249-L2277

Yes, I noticed the same thing. It’s possible to use a mix of Trusty and Xenial, like they do here:

https://github.com/travis-ci/travis-ci/issues/9815#issuecomment-402045581

**Comment by esabol** [comment]
> It’s possible to use a mix of Trusty and Xenial....

I have this working here:
https://travis-ci.org/esabol/gearmand/builds/526648235

(I've also added builds using clang-7 and clang-8.)

Any objections to switching to Xenial for all builds except for gcc 4.9.x? If not, I'll submit a PR.

**Comment by SpamapS** [comment]
If there's no supported gcc-4.9 on Travis, then I don't think we should support gcc-4.9 anymore. For simplicity, can we just use Xenial and narrow the travis scope?

**Comment by esabol** [comment]
Travis isn't taking Trusty away. It's just changing the default distribution to Xenial because Ubuntu isn't going to be updating the packages for Trusty.

I don't think we should stop Travis CI builds with gcc-4.9 quite yet. RHEL/CentOS 7.x is still using gcc 4.8.5. If anything, we should do CI builds with gcc 4.8, but 4.9 is probably close enough.

**Comment by SpamapS** [comment]
If Travis offers CentOS 7, let's run tests on that. Otherwise, I'm disinclined to spend energy making sure gearmand works on trusty when nobody should be using trusty.

**Comment by esabol** [comment]
Travis CI only supports Ubuntu distributions.

**Comment by SpamapS** [comment]
Bummer. Maybe it's time to consider some other CI system that will let us run in containers or something.

**Comment by esabol** [comment]
There is a way to use Docker in Travis CI, but it's currently considerted to be experimental and there's no documentation for it. I know Docker is available under Xenial in Travis CI.

**Comment by esabol** [comment]
Please go here: https://travis-ci.org/gearman/gearmand/builds/533563490 and restart the 297.4 and 297.8 builds. Or give me access to do so! :)
