### ISSUE TITLE
Warning: GearmanClient::doNormal(): send_packet(GEARMAN_COULD_NOT_CONNECT) Failed to send server-options packet -> libgearman/connection.cc:485

### ISSUE THREAD

**Issue by vudinhnghia** [gearman/gearmand#242]
Hi all,
I'm studying gearman. 
This is my code: 
- Client: 
$client = new GearmanClient();
	try{
		$client->addServer("127.0.0.1", "4730");
                print $client->doNormal("reverse", "Test 1");
	}
	catch(Exception $e){
		print_r($e);
	}
- Worker: 
      $worker = new GearmanWorker();
	$worker->addServer('127.0.0.1', '4730');
	$worker->addFunction("reverse", function ($job) {
		echo $job->workload();
	  return strrev($job->workload());
	});
	while ($worker->work());

When i run code on terminate then sucess.
 But i use browser, i see error:
 Warning: GearmanClient::doNormal(): send_packet(GEARMAN_COULD_NOT_CONNECT) Failed to send server-options packet -> libgearman/connection.cc:485 .
Environment:
 OS: centos 6,
gearman: 1.1.8
php: 5.6
Please, help me! Thanks

**Comment by esabol** [comment]
This isn't the repository for the PHP extension, so I will refer to you to them. Nothing in the above post specifically shows a problem with gearmand. Even if it did, gearmand 1.1.8 is extremely old, as is CentOS 6, which we don't really support. I will suggest that you that you should make sure gearmand is running by checking the appropriate port number with lsof and you should check the gearmand log file, which you should set to DEBUG or VERBOSE. Append `--verbose DEBUG -l /path/to/gearmand.log` to your gearmand arguments. Good luck!

**Comment by SpamapS** [comment]
Agree with @esabol .. not sure there's anything we can do for you here.
