### ISSUE TITLE
Gearmand Configuration File

### ISSUE THREAD

**Issue by LudovicLachance** [gearman/gearmand#243]
I did not find any description as to how the file passed to the --config-file option should be written.

Could someone point me to one or write me one?

**Comment by DarthEd77** [comment]
According to a message posted on the gearmand Google Group by Brian Aker, “It uses the same syntax as the command line arguments.”

**Comment by esabol** [comment]
According to a message posted on the gearmand Google Group by Brian Aker, “It uses the same syntax as the command line arguments.”

**Comment by LudovicLachance** [comment]
Well, that doesn't help at all, as there is no working example, whatever I try to do It always fails to load the configuration file. Why does it even says it support file, if it does not.

**Comment by p-alik** [comment]
Please post your config file, command you use to start `gearmand` and error message get.
Feel free to reopen the issue.
