### ISSUE TITLE
performance comparison

### ISSUE THREAD

**Issue by rspadim** [gearman/gearmand#244]
hi folks
could be possible create a perfomance comparison between some job queues systems and gearman with high job/seq work load?

**Comment by SpamapS** [comment]
You're welcome to perform such a test. Gearman is not really intended to compete with any others that I've seen. It either puts everything in RAM with frontend jobs (not fair to compare to durable systems) or stores background jobs in slow databases (it will lose horribly).

Gearman's super powers come in the clients and protocol, sort of like memcached, and as such, a pure test of its queue delivery performance will not really accurately represent what gearman can and cannot do.

As such, I'm going to close this, as it's not really an "issue", but I appreciate you asking the question, and you can feel free to comment again or open another more specific issue. Thanks for your interest in Gearman!
