### ISSUE TITLE
How do I return a background job to the queue if it fails?

### ISSUE THREAD

**Issue by webomax** [gearman/gearmand#251]
If there is a task execution error, I want the task not to be removed from the queue. And started again.

**Comment by p-alik** [comment]
> If there is a task execution error, I want the task not to be removed from the queue. And started again.

`gearmand` doesn't restart failed jobs. By non-background approach it is possible to provide worker's notifications to the client.  

See WORK_FAIL, WORK_EXCEPTION in http://gearman.org/protocol/

**Comment by webomax** [comment]
Must do for background job.

It turns out that Geraman will not restart the work in any way? Even if the background work is not successful, will it still remove it from the queue ?!

**Comment by p-alik** [comment]
> It turns out that Geraman will not restart the work in any way? 

Indeed `gearmand` doesn't restart any jobs.

**Comment by esabol** [comment]
Does the `--job-retries=NUMBER` option not do this?
