### ISSUE TITLE
PHP PECL library 

### ISSUE THREAD

**Issue by tsmgeek** [gearman/gearmand#252]
https://pecl.php.net/package/gearman

Not sure who is maintaining this but might be an idea to bring it in as its currently quite old and its throwing errors within the library itself rather than setting exceptions etc that can be handled in a sane way.

**Comment by esabol** [comment]
We don’t maintain that here. AFAIK, the best maintained version can be found here:

https://github.com/wcgallego/pecl-gearman

I use a modified version of that repo in a production environment without any issues.
