### ISSUE TITLE
I cannot use libmemcached as the "Persistent Queues"

### ISSUE THREAD

**Issue by zhyee** [gearman/gearmand#26]
I have installed the libmemcached library, but when I install gearmand and run "./configure", it's show info like below :
   
 LDFLAGS Flags:             
   * Assertions enabled:        no
   * Debug enabled:             no
   * Warnings as failure:       no
   * Building with libsqlite3   no
   * Building with libdrizzle   yes
   * Building with libmemcached not found
   * Building with libpq        no
   * Building with tokyocabinet no
   * Building with libmysql     no
   * SSL enabled:               no
   * cyassl found:              no
   * openssl found:             yes
   * make -j:                   2
   * VCS checkout:              no
   * sphinx-build:              :

Thus I finish to install gearmand , "libmemched persistence" cannot be used. below is the error:

**[root@localhost gearmand-1.1.12]# /usr/local/gearmand/sbin/gearmand -q libmemcached --libmemcached-servers=127.0.0.1**
**/usr/local/gearmand/sbin/gearmand: unknown option libmemcached-servers**

This is my libmemcached installed
**[root@localhost libmemcached]# ls /usr/local/libmemcached/
bin  include  lib  share**

I now have no idear to solve this issue, is anyone can help me!

**Comment by SpamapS** [comment]
Hi! You'd need to have libmemcached.a in your ld.so path, such as `/usr/local/lib`, for the configure script to find it. Or you can add `--with-libmemcached=/usr/local/libmemcached`
