### ISSUE TITLE
libtest/http.c crashed if CXXFLAGS contains '-Wp,-D_GLIBCXX_ASSERTIONS'

### ISSUE THREAD

**Issue by cheese** [gearman/gearmand#278]
The cause is the same with #272. There are three occurrences of `&_body[0]`.

**Comment by p-alik** [comment]
Indeed. As @esabol [mentioned](https://github.com/gearman/gearmand/issues/272#issuecomment-586751199) you'll see it often.

**Comment by esabol** [comment]
PR #281 submitted for this. Please take a look @cheese. It seemed to fix the issue in my Fedora 31 build in Docker.
```Dockerfile
FROM fedora:31

MAINTAINER gearmand

# Install packages
RUN dnf makecache
RUN dnf update -y
RUN dnf install -y 'dnf-command(builddep)' rpm-build git
RUN dnf install -y libtool autoconf automake
RUN dnf install -y make gettext-devel
RUN dnf install -y python3-sphinx
RUN dnf builddep -y gearmand
RUN dnf install -y mock
RUN useradd build && usermod -a -G mock build

ARG GEARMAN_REPO=https://github.com/gearman/gearmand

RUN cd /tmp && git clone --depth 1 --branch master ${GEARMAN_REPO}.git
WORKDIR /tmp/gearmand
RUN ./bootstrap.sh -a
ENV CXXFLAGS='-Wp,-D_GLIBCXX_ASSERTIONS'
COPY http.cc libtest/
RUN ./configure --enable-ssl 2>&1 | tee ./configure.log
RUN make 2>&1 | tee ./build.log
RUN make test 2>&1 | tee ./test.log
```

**Comment by esabol** [comment]
PR #281 has been merged. I think that addresses this issue? @cheese, can you test it?

I'm still planning to add `CXXFLAGS=-Wp,-D_GLIBCXX_ASSERTIONS` to our gcc-9 builds to catch this in the future.

**Comment by cheese** [comment]
> PR #281 has been merged. I think that addresses this issue? @cheese, can you test it?

I tested the latest code and the tests all goes well.
