### ISSUE TITLE
t/vector fails on 32bit platforms at ASSERT_FALSE(vec.resize(INT64_MAX))

### ISSUE THREAD

**Issue by cheese** [gearman/gearmand#279]
Are 32bit platforms still supported?

Tested 1.1.19.1 on 32bit CentOS7 altarch, and t/vector failed during `make test`.
The same on 32bit ARM.

The only failing assertion is `ASSERT_FALSE(vec.resize(INT64_MAX))`.

This Dockerfile can reproduce the issue:

```
FROM i386/centos:7

MAINTAINER gearmand

ARG GEARMAN_REPO=https://github.com/gearman/gearmand

LABEL version="${version}" description="Gearman SSL Job Server Image"

# Configure environment
ENV HOME=/root

# Install packages
RUN yum update -y
RUN yum install -y rpm-build make
RUN yum install -y boost-devel boost-thread gcc-c++ gperf  gperftools-devel  hiredis-devel  libevent-devel  libmemcached-devel  libpq-devel \
  libuuid-devel  mariadb-connector-c-devel  memcached  openssl-devel  sqlite-devel  systemd  tokyocabinet-devel  zlib-devel

# Retrieve the source code and bootstrap
COPY gearmand-1.1.19.1.tar.gz /tmp/
RUN cd /tmp && tar fx gearmand-1.1.19.1.tar.gz
WORKDIR /tmp/gearmand-1.1.19.1

RUN ./configure --enable-ssl 2>&1 | tee ./configure.log
RUN make 2>&1 | tee ./build.log
RUN make test 2>&1 | tee ./test.log
```

**Comment by p-alik** [comment]
> Tested 1.1.19.1 on 32bit CentOS7 altarch, and t/vector failed during make test.
> The same on 32bit ARM.

There are `{U,}INT64` [type checks](https://www.gnu.org/software/autoconf/manual/autoconf-2.64/html_node/Generic-Types.html)
https://github.com/gearman/gearmand/blob/a6bd168ca73bd29d0bf13ad946034957f9c86546/configure.ac#L188-L205

Shouldn't it cause an exception on 32bit system?

> The only failing assertion is ASSERT_FALSE(vec.resize(INT64_MAX)).

The assertion has a long history 255137a0e.

**Comment by esabol** [comment]
This is not specific to 1.1.19, right? This applies to 1.1.18, 1.1.17, etc., too?

**Comment by p-alik** [comment]
yes

**Comment by esabol** [comment]
> The only failing assertion is ASSERT_FALSE(vec.resize(INT64_MAX)).

If this is the only thing that fails, then that is easily fixed, right?

Is there any reason _not_ to support 32-bit architectures?

**Comment by SpamapS** [comment]
Quoting Ed Sabol (2020-02-22 17:07:05)
>      The only failing assertion is ASSERT_FALSE(vec.resize(INT64_MAX)).
> 
>    If this is the only thing that fails, then that is easily fixed, right?
> 
>    Is there any reason not to support 32-bit architectures?
> 

There will be relevant 32-bit arches for many years to come.

This is an easy fix with a conditional define. I don't have time, but
yes, somebody should fix this.

**Comment by esabol** [comment]
So I *think* this works on both 32-bit and 64-bit systems:
```C++
    // SIZE_MAX is ((size_t)(-1)), but we need to subtract 1 because the
    // gearman_vector_st implementation adds 1 to the capacity.
    ASSERT_FALSE(vec.resize(((size_t)(-1)) -1));
```
Anyone see a problem with that?

Otherwise, things get complicated:
```C++
#if defined(__LP64__) || defined(_WIN64) || (defined(__x86_64__) && !defined(__ILP32__)) || defined(_M_X64) || defined(__ia64) || defined (_M_IA64) || defined(__aarch64__) || defined(__powerpc64__)
    ASSERT_FALSE(vec.resize(INT64_MAX));
#else
    // SIZE_MAX is ((size_t)(-1)), but we need to subtract 1 because the
    // gearman_vector_st implementation adds 1 to the capacity.
    ASSERT_FALSE(vec.resize(((size_t)(-1)) -1));
#endif
```
References:
https://stackoverflow.com/a/40033930/5153779
https://stackoverflow.com/a/44401992/5153779

Should we bother to rename `INT64_MAX_resize_TEST` to something else?

**Comment by p-alik** [comment]
> Anyone see a problem with that?

LGTM. My worry is, that we haven't 32 CI environment for testing.

> Should we bother to rename `INT64_MAX_resize_TEST` to something else?

Wouldn't it be appropriate to cut off `INT64` prefix?

**Comment by cheese** [comment]
> Anyone see a problem with that?

In C++ style, it would be better to use `std::numeric_limits<size_t>::max()` instead of `((size_t)(-1))`.

> 
> Otherwise, things get complicated:
> 
> ```c++
> #if defined(__LP64__) || defined(_WIN64) || (defined(__x86_64__) && !defined(__ILP32__)) || defined(_M_X64) || defined(__ia64) || defined (_M_IA64) || defined(__aarch64__) || defined(__powerpc64__)
>     ASSERT_FALSE(vec.resize(INT64_MAX));
> #else
>     // SIZE_MAX is ((size_t)(-1)), but we need to subtract 1 because the
>     // gearman_vector_st implementation adds 1 to the capacity.
>     ASSERT_FALSE(vec.resize(((size_t)(-1)) -1));
> #endif
> ```
What's the real intention of using `INT64_MAX`? The generic of `INT64_MAX` seems `std::numeric_limits<ssize_t>::max()` instead of `std::numeric_limits<size_t>::max()`.

**Comment by esabol** [comment]
In reply to @p-alik's comment:
> My worry is, that we haven't 32 CI environment for testing.

Yeah. I've tested it with a Docker i386/centos7 image similar to what @cheese posted above, fwiw. I think it is possible to add Docker builds to Travis CI, but I don't know how. I think it's not worth the effort.

> > Should we bother to rename `INT64_MAX_resize_TEST` to something else?
> 
> Wouldn't it be appropriate to cut off `INT64` prefix?

Sure, that would be appropriate.

In reply to @cheese's comment: 
> In C++ style, it would be better to use `std::numeric_limits<size_t>::max()` instead of `((size_t)(-1))`.

Interesting. I'll test that (maybe later today) and report back.

> What's the real intention of using `INT64_MAX`?

I'm not sure any of us can answer that question since I'm guessing these tests were written before any of us got involved with gearmand. I think the intent is to just test `resize()` with the largest possible number it can take.

>  The generic of `INT64_MAX` seems `std::numeric_limits<ssize_t>::max()` instead of `std::numeric_limits<size_t>::max()`.

Is that a significant distinction?

**Comment by cheese** [comment]
> > The generic of `INT64_MAX` seems `std::numeric_limits<ssize_t>::max()` instead of `std::numeric_limits<size_t>::max()`.
> 
> Is that a significant distinction?

If your guess of the test intent is right, the argument should be `std::numeric_limits<size_t>::max() - 1`. But the original used INT64_MAX, which is much less than `std::numeric_limits<size_t>::max() - 1` on x86_64. The original author may just use a large enough argument instead of the largest possible one.

**Comment by esabol** [comment]
So this issue has languished. Rereading the thread here, I'm still not clear what the solution is. I think I'm still inclined to go with @cheese's suggestion of `std::numeric_limits<size_t>::max() - 1`. Anyone else have an opinion?

**Comment by p-alik** [comment]
I'm of the same opinion because it is most appropriate for the purpose of test.

https://github.com/gearman/gearmand/blob/36c1e2348b1dcde7b446307e768f3756ab537947/libgearman/vector.hpp#L89

**Comment by esabol** [comment]
Merged commit addresses this issue, so I’m going to close this.
