### ISSUE TITLE
error: 'environ' was declared 'extern' and later 'static' [-fpermissive]

### ISSUE THREAD

**Issue by gitHusband** [gearman/gearmand#292]
Hi!

I am Devin.

 I try to build gearmand-1.1.18 or gearmand-1.1.19 or gearmand-1.1.19.1. The same error I got.

ENV:
Docker Alpine, gcc 9.3.0

Can you help to investigate? Thanks!

 CXX      libtest/libtest_libtest_la-collection.lo
**libtest/cmdline.cc:65:15: error: 'environ' was declared 'extern' and later 'static' [-fpermissive]**
   65 | static char **environ= NULL;
      |               ^~~~~~~
In file included from ./libtest/common.h:77,
                 from libtest/cmdline.cc:39:
/usr/include/unistd.h:183:15: note: previous declaration of 'environ'
  183 | extern char **environ;
      |               ^~~~~~~
make[2]: *** [Makefile:6951: libtest/libtest_libtest_la-cmdline.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/tmp/gearmand-1.1.19.1'
make[1]: *** [Makefile:8322: all-recursive] Error 1
make[1]: Leaving directory '/tmp/gearmand-1.1.19.1'
make: *** [Makefile:3085: all] Error 2

**Comment by p-alik** [comment]
#289 the bug fix for the issue was merged into [master](https://github.com/gearman/gearmand/tree/master) branch last week. Try to build [master](https://github.com/gearman/gearmand/tree/master) source, please.

**Comment by gitHusband** [comment]
Great! Thanks! I'll try to build master.
