### ISSUE TITLE
Delete stale branches?

### ISSUE THREAD

**Issue by esabol** [gearman/gearmand#298]
Hi, @SpamapS and @p-alik. Can I delete the following stale gearman/gearmand branches? 

upstream_master: Updated 4 years ago by mestia -- Any idea what this is?
SpamapS-testing-bonnyci: Updated 3 years ago by SpamapS

Reference: https://github.com/gearman/gearmand/branches

**Comment by p-alik** [comment]
I have no objections

**Comment by SpamapS** [comment]
Do it!

**Comment by esabol** [comment]
Done! Closing issue.
