### ISSUE TITLE
IPv6 patch from Launchpad?

### ISSUE THREAD

**Issue by esabol** [gearman/gearmand#304]
There’s a short little patch over at https://bugs.launchpad.net/bugs/1319250 that addresses “corruption of IPv6 addresses in gearadmin --workers and log output“. Should we merge this?

Seems valid based on my reading of https://stackoverflow.com/questions/16010622/reasoning-behind-c-sockets-sockaddr-and-sockaddr-storage

**Comment by p-alik** [comment]
I do not have any objection to apply the patch to libgearman-server/gearmand.cc. But it would be advisable to have tests for that.

According to [socket man page](https://www.man7.org/linux/man-pages/man7/socket.7.html)

>       The sockaddr_storage structure is useful in programs that must handle
>       socket addresses in a generic way (e.g., programs that must deal with
>       both IPv4 and IPv6 socket addresses).

But there are critical notes with regard to the `struct sockaddr_storage` https://github.com/joyent/libuv/issues/430

**Comment by esabol** [comment]
Seeing as how IPv6 testing relies on the network configuration of the host, I think adding tests that work consistently may prove difficult.

**Comment by esabol** [comment]
A PR addressing this issue has been merged, so closing.
