### ISSUE TITLE
Build sign key

### ISSUE THREAD

**Issue by illuusio** [gearman/gearmand#310]
This can be just me but I can't find easily a build key to verify supplied .asc-file (which is very nice  to provide by the way!)
This should be in README.md or somewhere easily enough available.

**Comment by SpamapS** [comment]
My key is all over the place.. https://fewbar.com/clint-byrum-public-key/ and signed by many reputable keys.

**Comment by esabol** [comment]
I think it’s a reasonable request to add that link to the README.md. I’ll take care of that.

**Comment by SpamapS** [comment]
That's kind of pointless but I won't fight it.

If you trust the Readme you trust the asc file, as they're both verified by
the same method: GitHub.

**Comment by illuusio** [comment]
@SpamapS  Actually As a fle.. link does not work.. no big deal as I can copy'n'paste but just my few cents and thanks for adding @esabol it makes some other package maintener work easier.

**Comment by SpamapS** [comment]
Right.. but to be clear, it's not easy, because you should be verifying the
signing key *by multiple vectors*. Currently you are 100% dependent on
GitHub for that. It's a relatively safe bet, but I went through the trouble
of getting my key signed so you could use the distributed web of trust. :)
