### ISSUE TITLE
Segmentation fault (core dumped) on php 7.4.3

### ISSUE THREAD

**Issue by stccorp** [gearman/gearmand#322]
Hello,

I was working on moving from Ubuntu 18 to Ubuntu 20.  By default I am getting php 7.4.3 instead of  7.4.24 on ubuntu 20
Funny thing is that at this point in time 7.4.3 is not even on their website.  In any case,  I always run the gearman demo client to reverse a string.  On this new 7.4.3 I am getting a Segmentation fault (core dumped) on php 7.4.3. 

I am using libgearman version => 1.1.19.1+ds

So it works on 7.4.24 but it fails on 7.4.3  any ideas?  anyone tried to run on 7.4.3?

```
# php -f test_gearman.php
Sending job
Success: !olleH
Segmentation fault (core dumped)
```

I tried php version 8.0.11 and it works fine

Thank you

**Comment by stccorp** [comment]
It was solved by adding  this repository as someone here suggested in another thread

add-apt-repository ppa:ondrej/php -y && \
    apt-get update && \
    apt-get install -y -q php-gearman

**Comment by esabol** [comment]
Well, I'm glad you were able to fix it. Cool.

I think you posted to the wrong GitHub repo though? I think you wanted https://github.com/php/pecl-networking-gearman/ for PHP issues.
