### ISSUE TITLE
gearman can't use redis as persistence queue 

### ISSUE THREAD

**Issue by chenzi2015** [gearman/gearmand#33]
**Version:** 
gearmand 1.1.13

**Start gearmand command:**
exec start-stop-daemon --start --chuid gearman --exec /usr/sbin/gearmand -- --log-file=/var/log/gearman-job-server/gearman.log -q redis --redis-server 192.168.99.100 --redis-port 32768

Got error:
  ERROR 2016-11-16 10:24:38.000000 [  main ] Failed to call KEYS during QUEUE replay _hiredis_replay(QUEUE_ERROR) -> libgearman-server/plugins/queue/redis/queue.cc:258
  ERROR 2016-11-16 10:24:38.000000 [  main ] failed to reload queue gearmand_run(QUEUE_ERROR) -> libgearman-server/gearmand.cc:395
  ERROR 2016-11-16 10:24:38.000000 [  main ] Failed to call KEYS during QUEUE replay _hiredis_replay(QUEUE_ERROR) -> libgearman-server/plugins/queue/redis/queue.cc:258
  ERROR 2016-11-16 10:24:38.000000 [  main ] failed to reload queue gearmand_run(QUEUE_ERROR) -> libgearman-server/gearmand.cc:395
  ERROR 2016-11-16 10:24:38.000000 [  main ] Failed to call KEYS during QUEUE replay _hiredis_replay(QUEUE_ERROR) -> libgearman-server/plugins/queue/redis/queue.cc:258
  ERROR 2016-11-16 10:24:38.000000 [  main ] failed to reload queue gearmand_run(QUEUE_ERROR) -> libgearman-server/gearmand.cc:395
  ERROR 2016-11-16 10:24:38.000000 [  main ] Failed to call KEYS during QUEUE replay _hiredis_replay(QUEUE_ERROR) -> libgearman-server/plugins/queue/redis/queue.cc:258
  ERROR 2016-11-16 10:24:38.000000 [  main ] failed to reload queue gearmand_run(QUEUE_ERROR) -> libgearman-server/gearmand.cc:395
  ERROR 2016-11-16 10:24:38.000000 [  main ] Failed to call KEYS during QUEUE replay _hiredis_replay(QUEUE_ERROR) -> libgearman-server/plugins/queue/redis/queue.cc:258
  ERROR 2016-11-16 10:24:38.000000 [  main ] failed to reload queue gearmand_run(QUEUE_ERROR) -> libgearman-server/gearmand.cc:395
  ERROR 2016-11-16 10:24:38.000000 [  main ] Failed to call KEYS during QUEUE replay _hiredis_replay(QUEUE_ERROR) -> libgearman-server/plugins/queue/redis/queue.cc:258
  ERROR 2016-11-16 10:24:38.000000 [  main ] failed to reload queue gearmand_run(QUEUE_ERROR) -> libgearman-server/gearmand.cc:395
  ERROR 2016-11-16 10:24:38.000000 [  main ] Failed to call KEYS during QUEUE replay _hiredis_replay(QUEUE_ERROR) -> libgearman-server/plugins/queue/redis/queue.cc:258
  ERROR 2016-11-16 10:24:38.000000 [  main ] failed to reload queue gearmand_run(QUEUE_ERROR) -> libgearman-server/gearmand.cc:395
  ERROR 2016-11-16 10:24:38.000000 [  main ] Failed to call KEYS during QUEUE replay _hiredis_replay(QUEUE_ERROR) -> libgearman-server/plugins/queue/redis/queue.cc:258
  ERROR 2016-11-16 10:24:38.000000 [  main ] failed to reload queue gearmand_run(QUEUE_ERROR) -> libgearman-server/gearmand.cc:395

SO, I can't start up gearmand server!

**Comment by SpamapS** [comment]
Hi! We landed a ton of improvements in master a few weeks ago. I'll get a 1.1.14 release cut soon that should address this problem.

**Comment by SpamapS** [comment]
1.1.14 is released. Can you please confirm whether or not 1.1.14 fixes the issue for you?

**Comment by chenzi2015** [comment]
I download from https://github.com/gearman/gearmand/releases/download/1.1.14/gearmand-1.1.14.tar.gz  

**"./configure" Got error:** 
checking whether C++ compiler accepts -Wunused... yes
checking whether C++ compiler accepts -Wunused-result... yes
checking whether C++ compiler accepts -Wunused-variable... yes
checking whether C++ compiler accepts -Wunused-parameter... yes
checking whether C++ compiler accepts -Wunused-local-typedefs... yes
checking whether C++ compiler accepts -Wwrite-strings... yes
checking whether C++ compiler accepts -Wformat-security... yes
checking whether C++ compiler accepts -fwrapv... yes
checking whether C++ compiler accepts -fmudflapt... no
checking whether C++ compiler accepts -pipe... yes
checking whether C++ compiler accepts -fPIE... yes
checking whether C++ compiler accepts -pie... yes
checking whether C++ compiler accepts -Wsizeof-pointer-memaccess... yes
checking whether C++ compiler accepts -Wpacked... yes
checking whether the compiler supports GCC C++ ABI name demangling... yes
checking checking for cxx_gcc_abi_demangle... "yes"
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: error: cannot find input file: `libhashkit/hashkitcon.h.in'
root@6lappphpdev:~/gearmand-1.1.14# ls

I find no libhashkit directory in "gearmand-1.1.14"  root.

**Comment by chenzi2015** [comment]
Tanks, 1.1.14 this version has solved this problem.

but, can you add "redis-password" option of to connection to redis ?

**Comment by SpamapS** [comment]
Thanks for testing! Can you open a new issue for the missing redis-password option? Also, it's not a super hard change, maybe you can submit a patch? I don't really know how redis works and rely on redis users to support and maintain that part of gearmand.
