### ISSUE TITLE
Confusing: --show-unique-jobs explainer in gearadmin --help

### ISSUE THREAD

**Issue by octavn** [gearman/gearmand#335]
From the `gearadmin --help` output one might get the impression that gearman does not deduplicate jobs and that it holds internally a number of jobs that could be greater than the number of unique jobs (all-duplicate=unique):

```bash
  --show-unique-jobs             Show unique jobs on server.
  --show-jobs                    Show all jobs on the server.
```

The `gearadmin --show-unique-jobs` command [collects the unique jobs information from the `show unique jobs` command](https://github.com/gearman/gearmand/blob/master/bin/gearadmin.cc#L231) available in the [gearmand TEXT protocol](https://github.com/gearman/gearmand/blob/master/docs/source/protocol/text.rst) which "List all of the unique job ids that the server currently is processesing or waiting to process.".

To avoid/remove the confusion, the above one liner explanation for `--show-unique-jobs` should be changed to "Show the unique ids for the jobs on the server" in https://github.com/gearman/gearmand/blob/master/bin/gearadmin.cc#L142.

**Comment by esabol** [comment]
I concur and have submitted PR #336 to address this issue.

**Comment by esabol** [comment]
Fix merged. Closing.
