### ISSUE TITLE
gearmand multiple instances

### ISSUE THREAD

**Issue by TechhDan** [gearman/gearmand#342]
I've compiled gearman from the tarball using version gearmand-1.1.19.1. Whenever i try to start gearmand i get two instances with one being forked from the parent. Is this normal? I thought it was just suppose to be one deamon process.

![GearMan](https://user-images.githubusercontent.com/11691784/172958564-cec2329c-2489-4901-968e-8a05d4330f72.png)

**Comment by esabol** [comment]
> Whenever i try to start gearmand i get two instances with one being forked from the parent.

Well, that's not what your screenshot is showing. That `lsof` output is showing that it's listening to both your computer's IPv4 and IPv6 addresses, and it's showing the same PID for both. If a child had forked from the parent, you'd see different PIDs.

What's the output of `ps auxgww | grep gearmand | grep -v grep` show?

**Comment by TechhDan** [comment]
Oh! totally missed the IP4 and IP6. Thanks for the tip. I had downloaded the apt version (v 1.1.18) and that one only showed one process so i thought something was wrong. Thanks!

![Gearman2](https://user-images.githubusercontent.com/11691784/172972721-43b993ea-b2e4-44de-bb23-459dea471552.png)

**Comment by esabol** [comment]
No problem! If only all issues could be easy. 🙂 Closing.
