### ISSUE TITLE
Tarballs created from master can't find libboost/config/workaround.hpp

### ISSUE THREAD

**Issue by SpamapS** [gearman/gearmand#355]
With latest master, if I create a tarball with "make dist" it produces a build that fails because the include dir for Boost isn't set in a way that finds workaround.hpp. AFAIK, that is a clang-thing anyway for Mac OS X. As such, I believe it needs to be surrounded by a guard.

We also should add a build-from-make-dist action so I'm not the only one who can see those, and maybe even at some point use that to publish release tarballs.

**Comment by esabol** [comment]
@SpamapS : Could you attach one such tarball here and/or supply instructions on how to reproduce it from a clean `git clone`?

**Comment by esabol** [comment]
Also, what OS are you generating the tarball on?

**Comment by SpamapS** [comment]
I've tried generating on Ubuntu 18.04, 20.04, and 22.04. Trying to build on all 3 as well. Building from git works fine so it's something that goes into the tarball.

**Comment by SpamapS** [comment]
[gearmand-1.1.19.1-76-gfaede598.tar.gz](https://github.com/gearman/gearmand/files/10009859/gearmand-1.1.19.1-76-gfaede598.tar.gz)

This was generated with: 

```docker run --rm -v $PWD:/usr/local/src -ti gearmand-testing/ubuntu:20.04 /bin/bash -c "cd /usr/local/src && CC=gcc-9 CXX=g++-9 ./configure --enable-ssl && make -j && make dist"```

**Comment by esabol** [comment]
> I've tried generating on Ubuntu 18.04, 20.04, and 22.04. Trying to build on all 3 as well. Building from git works fine so it's something that goes into the tarball.

I recommend trying on Ubuntu 16.04. Or I will, if I have time.

It's probably the same issue we saw with the 1.1.19 release. I imagine it's the files in the `m4` directory. The bootstrap process alters them, I think. Making a backup of the `m4` directory before and then copying some or all of the files in the `m4` directory back may ameliorate the problem? But that's not a good long-term solution.

**Comment by SpamapS** [comment]
Found it. I failed to notice that `libboost/config/workaround.hpp` was a file in our repo, but it isn't included in the tarball. Working on a fix.
