### ISSUE TITLE
How to check job queue in gearman

### ISSUE THREAD

**Issue by ananta-code** [gearman/gearmand#364]
Hi ,
I have deployed a container `artefactual/gearmand:latest` in kubernetes and it is successful and then i gearman jenkins plugin in my jenkins but i cant see build job queue in gearman container.

Could you please help me if any additional things are required to view the job queue ?
also how the jobs assigned to different controllers by gearman? Do i need to have configuration for that

**Comment by esabol** [comment]
@ananta-code asked:
> Hi , I have deployed a container `artefactual/gearmand:latest` in kubernetes and it is successful and then i gearman jenkins plugin in my jenkins but i cant see build job queue in gearman container.

Make sure you read issue #320 for configuring Kubernetes properly.

> Could you please help me if any additional things are required to view the job queue ?

Attach to the gearmand container and execute `gearadmin --status` or use telnet or netcat as described here:

https://stackoverflow.com/questions/3378760/how-can-i-get-the-number-of-queued-jobs-of-a-particular-type-in-gearman

> also how the jobs assigned to different controllers by gearman? Do i need to have configuration for that

The question does not make any sense. Gearman doesn't have "controllers". It has workers, clients, and servers.


Hope this helps!

**Comment by ananta-code** [comment]
I mean how to assign jobs from the gearman queue to different service.
For example i configured gearman plugin in both jenkins controllers (e.g server) ..when i trigger 10-15 builds i saw these builds are in queue in the jenkins however i tried gearadmin --status in gearmand container it is not displaying all these jobs which are in queue.

and also i want some jobs should be scheduled in another jenkins but it is not happening

**Comment by SpamapS** [comment]
Hi! I think you will want to contact the maintainers of the jenkins gearman plugin, we can't really decipher that status output beyond telling you there are no jobs in any of the queues, but one active worker in each.
