### ISSUE TITLE
Configure error when gperf is absent

### ISSUE THREAD

**Issue by ntrs** [gearman/gearmand#376]
If configure script cannot find gperf, it ends up with an error (at least on FreeBSD 13.2):
```
checking for gperf... no
./configure: 22415: Syntax error: Bad fd number
```

The line 22415 looks like this:
`>   as_fn_error $? "could not find gperf" "$LINENO" 5]`

There is a square bracket at the end of line, which seems to be doubled by mistake in configure.ac line 128:

https://github.com/gearman/gearmand/blob/56761cd7c6119cbfde81033f3371a551055390a3/configure.ac#L128

**Comment by esabol** [comment]
OK, so if you remove that extra square bracket, does it fix the error, @ntrs?

**Comment by ntrs** [comment]
@esabol, yes, configure doesn't stop at that point when I remove it.

**Comment by ntrs** [comment]
> Great catch! Do you want to submit a pull request?

I'm too lazy to learn how to do all that push/pull/sense/heal stuff :)
Maybe you could just hit DEL once when editing that file before next release...

**Comment by esabol** [comment]
> I'm too lazy to learn how to do all that push/pull/sense/heal stuff :)

OK, I’ll do it. Just wanted to give you the option since you found the fix. :smile:
