### ISSUE TITLE
gearman.org is gone

### ISSUE THREAD

**Issue by niftyhack** [gearman/gearmand#387]

**Comment by SpamapS** [comment]
I will fire off some emails to the parties that should own it. I'm not
actually sure if it's Brian or Brad or @dormando. But in the meantime I
think we can at least host it at gearmand.github.io with some settings
changes. I'll poke at it soon.

**Comment by BrianAker** [comment]
I never owned the gearman.org domain name.   It might have been/is owned by Dormando  or Brad.

	— Brian

**Comment by BrianAker** [comment]
The whois record shows that the domain is pointed at Linode's DNS infrastructure, which I did use years ago.

I suspect they must have done some sort of cleanup recently and purged a dangling reference to the domain.

If you know anyone who has a linode account, i.e. Akamai, you could probably just create a record in their DNS system and be good to go.

**Comment by SpamapS** [comment]
I grabbed gearman.io just in case and have temporarily moved the github pages to it. So for the moment, you can view the content at https://gearman.io

I'll continue to try and chase down who owns the domain and try to get some administrative control over it so we don't have more issues like this.

**Comment by esabol** [comment]
We also lost gearman.info well before this, according to the Wayback Machine, but it just hosted the gearmand documentation. I feel we should use GitHub for that, as in issue #141. I've been meaning to add a GitHub Action to do this, but issue #373 was an impediment last time I tried.

**Comment by esabol** [comment]
@SpamapS : If we can't get control of gearman.org back, the references to it in the repo will need to be changed to gearmand.io.

https://github.com/search?q=repo%3Agearman%2Fgearmand%20Gearman.org&type=code

**Comment by SpamapS** [comment]
Oh! I forgot about gearman.info. Thanks Ed. I'll take a look at the sphinx errors. 🤔 

We really should get together and have an in-person summit some day to pull all of this stuff together. I ran into a textbook Gearman use case at work this week and I'm realizing it still has a place in modern architectures but we haven't done a great job of promoting it.

**Comment by esabol** [comment]
> We also lost gearman.info well before this, according to the Wayback Machine, but it just hosted the gearmand documentation. I feel we should use GitHub for that, as in issue #141. I've been meaning to add a GitHub Action to do this, but issue #373 was an impediment last time I tried.

See PR #388. Feedback welcome.

**Comment by jimwins** [comment]
> If you know anyone who has a linode account, i.e. Akamai, you could probably just create a record in their DNS system and be good to go.

It isn't quite that easy, Linode reports “DNS zone already exists.” if you try and do that, so whatever account it was previously attached to must exist in some sort of zombie state.

Looks like the gearman.org registration doesn't lapse until 2029, so somebody may have sprung for a 10-year renewal some years ago. You can dig up a contact email through whois.gandi.net, maybe it will reach whoever is still hanging on to it.

**Comment by esabol** [comment]
> You can dig up a contact email through whois.gandi.net, maybe it will reach whoever is still hanging on to it.

OK, I emailed the registrant through gandi.net.

**Comment by bradfitz** [comment]
I own gearman.org still and have it paid up until 2029. It's still pointing at Linode as that's where I believe I was last told to point it.

<img width="645" alt="Screenshot 2024-04-04 at 9 02 12 PM" src="https://github.com/gearman/gearmand/assets/2621/0d2ceea2-6ce5-4998-a4eb-05f6719459c1">

Where should it point now?

I'm also happy to create a Route 53 zone for it if you only have IPs.

**Comment by SpamapS** [comment]
Hi Brad. We need gearman.org to be setup for GitHub pages. See https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site for the A and AAAA records to make that happen. It should be relatively static after that. Thanks!

**Comment by bradfitz** [comment]
k, moved DNS back to Route 53 (where it was years ago) at roots:

ns-1784.awsdns-31.co.uk.
ns-18.awsdns-02.com.
ns-1400.awsdns-47.org.
ns-905.awsdns-49.net.

And created the A and AAAA records there.

I have no access to do things here on GitHub of course, so hopefully y'all pressed the right buttons on this side.

I didn't create records for "www." because `https://gearman.org` is the old (and better :)) URL, but let me know if you need them for some reason.

**Comment by SpamapS** [comment]
Thanks Brad, as of a minute ago, it's working! Others please verify and we can close this.

**Comment by esabol** [comment]
Thanks, @bradfitz!

http://gearman.org/ is working great. My web browser is complaining about the certificate for https://gearman.org/ though. Not sure why.

**Comment by SpamapS** [comment]
New TLS certs take 15 minutes or so to propagate. Try again later and it should work OK.

**Comment by SpamapS** [comment]
I changed gearman.io to redirect to gearman.org just in case anyone saved it in this brief window.

**Comment by niftyhack** [comment]
A big thank you to everyone involved.

**Comment by SpamapS** [comment]
The website looks good ,and I also noticed we had some http:// links, but now they're either schemaless or https, so you should get the shield on every page.
