### ISSUE TITLE
gearmand 1.1.12 does not work with SQL persistence on Ubuntu 14.04

### ISSUE THREAD

**Issue by elfeffe** [gearman/gearmand#4]
Is there any good instructions to make it ork in Ubuntu 14.04?
Is possible with MySql persistence.
I have tried with the instructions provided in the website and looks to be very old, they don't work.

**Comment by p-alik** [comment]
mysql support is out of the box available.

- create a table:
```sql
CREATE TABLE `queue` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `unique_key` varchar(64) NOT NULL,
  `function_name` varchar(255) NOT NULL,
  `when_to_run` int(10) NOT NULL,
  `priority` int(10) NOT NULL,
  `data` longblob NOT NULL,
  PRIMARY KEY (`id`)
)
```
- start gearmand:

```bash
gearmand \
  --queue-type mysql \
  --mysql-host=127.0.0.1 \
  --mysql-user=XXX \
  --mysql-password=XXX \
  --mysql-db=gearman \
  --mysql-table=queue
```

**Comment by SpamapS** [comment]
docs/source/gearmand/queues/mysql.rst has instructions for using SQL persistence.

Please state what you did, what you expected to happen, and what actually happened, when opening issues, so we can address the issue.

**Comment by elfeffe** [comment]
it doesn't work with default Ubuntu 14.04 version (there is a bug, and gearman does not read the config file).
As documented here: http://jeremykendall.net/2014/09/04/ubuntu-14-dot-04-gearman-config-bug/
Then my gearman version is
`gearmand 1.1.12 - https://bugs.launchpad.net/gearmand`
I followed https://gist.github.com/himelnagrana/9758209 to install it
I start it using the instructions here https://github.com/gearman/gearmand/blob/master/docs/source/gearmand/queues/mysql.rst
And it creates the table, but there is no task in the table. The table is empty.
The log says
`  ERROR 2016-07-07 20:59:42.000000 [  main ] Timeout occured when calling bind() for 0.0.0.0:4730 -> libgearman-server/gearmand.cc:688`

**Comment by SpamapS** [comment]
Cool thanks for the details elfeffe. I'll take a look at that soon.

**Comment by p-alik** [comment]
> it doesn't work with default Ubuntu 14.04 version (there is a bug, and gearman does not read the config file).
> As documented here: http://jeremykendall.net/2014/09/04/ubuntu-14-dot-04-gearman-config-bug/

It's not a gearmand bug, but Ubuntu/Debian package:
> The bug shows up on Ubuntu 14.04 Trusty Tahr in Gearman version 1.0.6-3

solution in my [answer](#4#issuecomment-231198939) works fine without usage of Ubuntu/Debian package:

- create a job ```bash
gearman -f foo -b -I 123```
- kill gearmand
-  job is in the queue table
```sql
select *from queue;
+----+--------------------------------------+---------------+-------------+----------+------+
| id | unique_key                           | function_name | when_to_run | priority | data |
+----+--------------------------------------+---------------+-------------+----------+------+
|  1 | d9fd0342-44e8-11e6-a2f3-7446a09167b1 | foo           |           0 |        0 | 123  |
+----+--------------------------------------+---------------+-------------+----------+------+
```
- start gearmand
- start worker
```bash
gearman -w -f foo 
123
```
-  queue table is empty now

**Comment by SpamapS** [comment]
Indeed, this seems to work on the compiled version of gearmand. perhaps you could report this against the Ubuntu package?

**Comment by SpamapS** [comment]
No response for a while. I'm going to close this, but please re-open or open a new one if you have new information.
