### ISSUE TITLE
Is gearmand using getservbyname() correctly?

### ISSUE THREAD

**Issue by esabol** [gearman/gearmand#412]
[libgearman-server/plugins/protocol/gear/protocol.cc#L468](https://github.com/gearman/gearmand/blob/728f3a5ab58c2a580481e0a4f60f2316a6981ecf/libgearman-server/plugins/protocol/gear/protocol.cc#L468) says:
```
      gearman_servent= getservbyname(GEARMAN_DEFAULT_TCP_SERVICE, NULL)
      service= gearman_servent->s_name;
      _port.append(service);
```
The `s_name` parameter is the name of the service, I believe?

Should gearmand be using the `servent` property `_port` instead of `_name`?

**Comment by SpamapS** [comment]
No, it's a bit confusing, but I think the idea here is we look it up and
turn it into a port later in the startup, so we're just looking up the name
in case the system has a different one aliased for gearman.

**Comment by esabol** [comment]
Really? That seems very weird to me. Guess I'll close this an a non-issue then.
