### ISSUE TITLE
The docs link to "gearman.info" which has either been hacked or doesnt belong to the project

### ISSUE THREAD

**Issue by castaway** [gearman/gearmand#415]
https://github.com/gearman/gearmand/blob/c24d8998e409a5d7d90110eb4a88b9f5b69ae103/docs/source/gearmand.rst?plain=1#L285

Suggest replacing this with a gearman.org link

**Comment by esabol** [comment]
Yeah, we lost http://gearman.info/ at least a year ago, unfortunately. We didn't know it had been taken over by an Indonesian gambling site though. I also didn't realize we had so many references to gearman.info in the repository. I'll change them to gearman.org.

http://gearman.net/ is also not responding, but I don't think that was ever advertised.

**Comment by esabol** [comment]
Merged PR #416 in order to address this. Let me know if I missed any occurrences. Thank you, @castaway, for reporting it.
