### ISSUE TITLE
gearman.errors.ServerUnavailable: Found no valid connections in list

### ISSUE THREAD

**Issue by lookcat** [gearman/gearmand#46]
I use the  centOS6.5  and   python2.7.9,  start up with the command of gearmand -d , I 'm failed   all the time.   

log:
File "schedulerTask.py", line 345, in <module>
    gm_worker.work()
  File "/usr/local/lib/python2.7/site-packages/gearman/worker.py", line 83, in work
    continue_working = self.poll_connections_until_stopped(worker_connections, continue_while_connections_alive, timeout=poll_timeout)
  File "/usr/local/lib/python2.7/site-packages/gearman/connection_manager.py", line 203, in poll_connections_until_stopped
    raise ServerUnavailable('Found no valid connections in list: %r' % self.connection_list)
gearman.errors.ServerUnavailable: Found no valid connections in list: [<GearmanConnection ip:7003 connected=False>]

what'w wrong with me ?  
can you give me some advice?

**Comment by esabol** [comment]
You haven't provided enough information to diagnose your problem. The Python Gearman libraries are not under the purview of the gearmand project, so I doubt this is even the proper venue for your issue. I recommend that you check your gearmand log and your firewall configuration.

**Comment by lookcat** [comment]
I make the  inside network IP  to configure  the  file, I saw the some errors.
#########################################################################
root@iZ115fd3dixZ ~]# cat /var/log/gearmand.log
  ERROR 2016-11-25 03:16:15.000000 [  main ] socket()(Address family not supported by protocol) -> libgearman-server/gearmand.cc:468
  ERROR 2016-11-25 03:16:15.000000 [  main ] gearmand_sockfd_close() called with an invalid socket -> libgearman-server/io.cc:933
###########################################################################
I guess the issue that IP was wrong, so I replace the inside network IP , if works!
Thank for you help! Good day!
