### ISSUE TITLE
Add "prioritystatus" to report status broken down by priority

### ISSUE THREAD

**Issue by njam** [gearman/gearmand#53]
For monitoring our gearman server we would like to know how many jobs are currently queued, broken down by priority. Then we can alert quickly if high prio jobs are piling up.

Usage could look like this:
```
$ gearadmin --priority-status
HIGH	12	7
NORMAL	14	3
LOW	0	0
```
With these columns:
- Priority name
- Number in queue
- Number of jobs running

@SpamapS wrote on the [mailing list](https://groups.google.com/forum/#!topic/gearman/VsmELtjoRFM):
> we'd love to see a patch for that as an addition to the admin protocol. The information is definitely readily available in the data structure, since each priority is in fact its own linked list.

> Any patch would need to include updates to gearmand/PROTOCOL to explain the difference in the Administrative protocol.

cc @ppp0 @kris-lab @fvovan maybe something for the next Research Day (December 14th)?

**Comment by SpamapS** [comment]
Thanks for the submission. I actually think it needs to be broken down by function name.
