### ISSUE TITLE
centOS6.5 ,  mysql57   conflicts with gearmand

### ISSUE THREAD

**Issue by lookcat** [gearman/gearmand#55]
Transaction Check Error:
  file /usr/share/mysql/charsets/Index.xml from install of mysql-libs-5.1.73-7.el6.x86_64 conflicts with file from package mysql-community-common-5.7.15-1.el6.x86_64
  file /usr/share/mysql/charsets/armscii8.xml from install of mysql-libs-5.1.73-7.el6.x86_64 conflicts with file from package mysql-community-common-5.7.15-1.el6.x86_64
  file /usr/share/mysql/charsets/ascii.xml from install of mysql-libs-5.1.73-7.el6.x86_64 conflicts with file from package mysql-community-common-5.7.15-1.el6.x86_64
  file /usr/share/mysql/charsets/cp1250.xml from install of mysql-libs-5.1.73-7.el6.x86_64 conflicts with file from package mysql-community-common-5.7.15-1.el6.x86_64
  file /usr/share/mysql/charsets/cp1256.xml from install of mysql-libs-5.1.73-7.el6.x86_64 conflicts with file from package mysql-community-common-5.7.15-1.el6.x86_64
  file /usr/share/mysql/charsets/cp1257.xml from install of mysql-libs-5.1.73-7.el6.x86_64 conflicts with file from package mysql-community-common-5.7.15-1.el6.x86_64
  file /usr/share/mysql/charsets/cp850.xml from install of mysql-libs-5.1.73-7.el6.x86_64 conflicts with file from package mysql-community-common-5.7.15-1.el6.x86_64
  file /usr/share/mysql/charsets/cp852.xml from install of mysql-libs-5.1.73-7.el6.x86_64 conflicts with file from package mysql-community-common-5.7.15-1.el6.x86_64
  file /usr/share/mysql/charsets/cp866.xml from install of mysql-libs-5.1.73-7.el6.x86_64 conflicts with file from package mysql-community-common-5.7.15-1.el6.x86_64
  file /usr/share/mysql/charsets/dec8.xml from install of mysql-libs-5.1.73-7.el6.x86_64 conflicts with file from package mysql-community-common-5.7.15-1.el6.x86_64
  file /usr/share/mysql/charsets/geostd8.xml from install of mysql-libs-5.1.73-7.el6.x86_64 conflicts with file from package mysql-community-common-5.7.15-1.el6.x86_64
  file /usr/share/mysql/charsets/greek.xml from install of mysql-libs-5.1.73-7.el6.x86_64 conflicts with file from package mysql-community-common-5.7.15-1.el6.x86_64
  file /usr/share/mysql/charsets/hebrew.xml from install of mysql-libs-5.1.73-7.el6.x86_64 conflicts with file from package mysql-community-common-5.7.15-1.el6.x86_64
  file /usr/share/mysql/charsets/hp8.xml from install of mysql-libs-5.1.73-7.el6.x86_64 conflicts with file from package mysql-community-common-5.7.15-1.el6.x86_64
  file /usr/share/mysql/charsets/keybcs2.xml from install of mysql-libs-5.1.73-7.el6.x86_64 conflicts with file from package mysql-community-common-5.7.15-1.el6.x86_64
  file /usr/share/mysql/charsets/koi8r.xml from install of mysql-libs-5.1.73-7.el6.x86_64 conflicts with file from package mysql-community-common-5.7.15-1.el6.x86_64
  file /usr/share/mysql/charsets/koi8u.xml from install of mysql-libs-5.1.73-7.el6.x86_64 conflicts with file from package mysql-community-common-5.7.15-1.el6.x86_64
  file /usr/share/mysql/charsets/latin1.xml from install of mysql-libs-5.1.73-7.el6.x86_64 conflicts with file from package mysql-community-common-5.7.15-1.el6.x86_64
  file /usr/share/mysql/charsets/latin2.xml from install of mysql-libs-5.1.73-7.el6.x86_64 conflicts with file from package mysql-community-common-5.7.15-1.el6.x86_64
  file /usr/share/mysql/charsets/latin5.xml from install of mysql-libs-5.1.73-7.el6.x86_64 conflicts with file from package mysql-community-common-5.7.15-1.el6.x86_64
  file /usr/share/mysql/charsets/latin7.xml from install of mysql-libs-5.1.73-7.el6.x86_64 conflicts with file from package mysql-community-common-5.7.15-1.el6.x86_64
  file /usr/share/mysql/charsets/macce.xml from install of mysql-libs-5.1.73-7.el6.x86_64 conflicts with file from package mysql-community-common-5.7.15-1.el6.x86_64
  file /usr/share/mysql/charsets/macroman.xml from install of mysql-libs-5.1.73-7.el6.x86_64 conflicts with file from package mysql-community-common-5.7.15-1.el6.x86_64
  file /usr/share/mysql/charsets/swe7.xml from install of mysql-libs-5.1.73-7.el6.x86_64 conflicts with file from package mysql-community-common-5.7.15-1.el6.x86_64
  file /usr/share/mysql/czech/errmsg.sys from install of mysql-libs-5.1.73-7.el6.x86_64 conflicts with file from package mysql-community-common-5.7.15-1.el6.x86_64
  file /usr/share/mysql/danish/errmsg.sys from install of mysql-libs-5.1.73-7.el6.x86_64 conflicts with file from package mysql-community-common-5.7.15-1.el6.x86_64
  file /usr/share/mysql/dutch/errmsg.sys from install of mysql-libs-5.1.73-7.el6.x86_64 conflicts with file from package mysql-community-common-5.7.15-1.el6.x86_64
  file /usr/share/mysql/english/errmsg.sys from install of mysql-libs-5.1.73-7.el6.x86_64 conflicts with file from package mysql-community-common-5.7.15-1.el6.x86_64
  file /usr/share/mysql/estonian/errmsg.sys from install of mysql-libs-5.1.73-7.el6.x86_64 conflicts with file from package mysql-community-common-5.7.15-1.el6.x86_64
  file /usr/share/mysql/french/errmsg.sys from install of mysql-libs-5.1.73-7.el6.x86_64 conflicts with file from package mysql-community-common-5.7.15-1.el6.x86_64
  file /usr/share/mysql/german/errmsg.sys from install of mysql-libs-5.1.73-7.el6.x86_64 conflicts with file from package mysql-community-common-5.7.15-1.el6.x86_64
  file /usr/share/mysql/greek/errmsg.sys from install of mysql-libs-5.1.73-7.el6.x86_64 conflicts with file from package mysql-community-common-5.7.15-1.el6.x86_64
  file /usr/share/mysql/hungarian/errmsg.sys from install of mysql-libs-5.1.73-7.el6.x86_64 conflicts with file from package mysql-community-common-5.7.15-1.el6.x86_64
  file /usr/share/mysql/italian/errmsg.sys from install of mysql-libs-5.1.73-7.el6.x86_64 conflicts with file from package mysql-community-common-5.7.15-1.el6.x86_64
  file /usr/share/mysql/japanese/errmsg.sys from install of mysql-libs-5.1.73-7.el6.x86_64 conflicts with file from package mysql-community-common-5.7.15-1.el6.x86_64
  file /usr/share/mysql/korean/errmsg.sys from install of mysql-libs-5.1.73-7.el6.x86_64 conflicts with file from package mysql-community-common-5.7.15-1.el6.x86_64
  file /usr/share/mysql/norwegian-ny/errmsg.sys from install of mysql-libs-5.1.73-7.el6.x86_64 conflicts with file from package mysql-community-common-5.7.15-1.el6.x86_64
  file /usr/share/mysql/norwegian/errmsg.sys from install of mysql-libs-5.1.73-7.el6.x86_64 conflicts with file from package mysql-community-common-5.7.15-1.el6.x86_64
  file /usr/share/mysql/polish/errmsg.sys from install of mysql-libs-5.1.73-7.el6.x86_64 conflicts with file from package mysql-community-common-5.7.15-1.el6.x86_64
  file /usr/share/mysql/portuguese/errmsg.sys from install of mysql-libs-5.1.73-7.el6.x86_64 conflicts with file from package mysql-community-common-5.7.15-1.el6.x86_64
  file /usr/share/mysql/romanian/errmsg.sys from install of mysql-libs-5.1.73-7.el6.x86_64 conflicts with file from package mysql-community-common-5.7.15-1.el6.x86_64
  file /usr/share/mysql/russian/errmsg.sys from install of mysql-libs-5.1.73-7.el6.x86_64 conflicts with file from package mysql-community-common-5.7.15-1.el6.x86_64
  file /usr/share/mysql/serbian/errmsg.sys from install of mysql-libs-5.1.73-7.el6.x86_64 conflicts with file from package mysql-community-common-5.7.15-1.el6.x86_64
  file /usr/share/mysql/slovak/errmsg.sys from install of mysql-libs-5.1.73-7.el6.x86_64 conflicts with file from package mysql-community-common-5.7.15-1.el6.x86_64
  file /usr/share/mysql/spanish/errmsg.sys from install of mysql-libs-5.1.73-7.el6.x86_64 conflicts with file from package mysql-community-common-5.7.15-1.el6.x86_64
  file /usr/share/mysql/swedish/errmsg.sys from install of mysql-libs-5.1.73-7.el6.x86_64 conflicts with file from package mysql-community-common-5.7.15-1.el6.x86_64
  file /usr/share/mysql/ukrainian/errmsg.sys from install of mysql-libs-5.1.73-7.el6.x86_64 conflicts with file from package mysql-community-common-5.7.15-1.el6.x86_64
  file /etc/my.cnf from install of mysql-libs-5.1.73-7.el6.x86_64 conflicts with file from package mysql-community-server-5.7.13-1.el6.x86_64

I have no  idea  with the trouble,  give me some tip to kill  the error.

**Comment by p-alik** [comment]
It looks like a pure mysql installation issue. Please, provide more information if you are sure it is gearmand issue.

**Comment by SpamapS** [comment]
Indeed, @lookcat you will want to contact the CentOS/Fedora/RHEL package managers, that hs nothing to do with Gearman.
