### ISSUE TITLE
Error checking version boostlib

### ISSUE THREAD

**Issue by entermix** [gearman/gearmand#68]
I am trying to install an extension Gearman:

Operating System: Centos 7
PHP: 5.6.28

Perform the following steps:

```
wget https://launchpad.net/gearmand/1.2/1.1.11/+download/gearmand-1.1.12.tar.gz
tar -zxvf gearmand-1.1.12.tar.gz
cd gearmand-1.1.12
./configure
```

```
However, getting the error:
checking for boostlib> = 1.39 ... configure: We could not detect the boost libraries (version 1.39 or higher). If you have a staged boost library (still not installed) please specify $ BOOST_ROOT in your environment and do not give a PATH to --with-boost option. If you are sure you have boost installed, then check your version number looking in <boost / version.hpp>. See http://randspringer.de/boost for more documentation.
configure: error: could not find boost
```

More details: http://pastebin.com/NFpbq20c

However, I have set BOOST 1.53

```
cat /usr/include/boost/version.hpp | grep "BOOST_LIB_VERSION"
//  BOOST_LIB_VERSION must be defined to be the same as BOOST_VERSION
#define BOOST_LIB_VERSION "1_53"
```

Why is this happening and how can I fix this?

**Comment by esabol** [comment]
First off, if you are going to compile gearmand from source, you might as well get the latest version, which you can download from https://github.com/gearman/gearmand/releases

Secondly, if you used yum to install boost, you probably didn't install the "devel" package. Try "sudo yum install boost-devel.x86_64" or similar.

**Comment by gmr** [comment]
FWIW I see this same issue when compiling from scratch, using Alpine Linux:

```
checking for boostlib >= 1.39... configure: We could not detect the boost libraries (version 1.39 or higher). If you have a staged boost library (still not installed) please specify $BOOST_ROOT in your environment and do not give a PATH to --with-boost option.  If you are sure you have boost installed, then check your version number looking in <boost/version.hpp>. See http://randspringer.de/boost for more documentation.
configure: error: could not find boost
```

```
/tmp/gearmand-1.1.14 # cat /usr/include/boost/version.hpp  |grep BOOST_LIB_VERSION
//  BOOST_LIB_VERSION must be defined to be the same as BOOST_VERSION
#define BOOST_LIB_VERSION "1_60"
```

**Comment by esabol** [comment]
The existence of /usr/include/boost/version.hpp doesn't mean you have everything you need to compile programs that use boost.

**Comment by gmr** [comment]
I had installed it. I ended up finding out that someone's already packaged it in their testing repo. To get it installed, I do the following now:

```bash
echo "@testing http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
apk add --update gearmand@testing gearman-dev@testing
```

Here is the repo with what they patched and the compilation options for the curious:

http://git.alpinelinux.org/cgit/aports/tree/testing/gearmand?id=668180c0ce66281b7bb9b307d1130585b7d7cb87

**Comment by esabol** [comment]
They didn't do anything special except install the boost-dev package, which is what I suggested. Anyway, glad you found a solution.

**Comment by SpikedCola** [comment]
I have the same issue with boost when compiling 1.1.14 on Raspbian, even after installing `libboost-all-dev`

The workaround I found was to specify the boost lib directory when calling configure:
`./configure --with-boost-libdir=/usr/lib/arm-linux-gnueabihf/`

**Comment by BasBastian** [comment]
Hi. Did you try boost-program-options or similar package? 

https://www.rpmfind.net/linux/rpm2html/search.php?query=boost-program-options

That is usually missing from dependencies downloaded before building and causes `make` prematurely assume that libboost dependency has been resolved, which is not true.

**Comment by SpamapS** [comment]
Bump. I am not sure if we can do anything for this one. Feels like maybe a dead issue.

**Comment by drook** [comment]
There's clearly something broken in autotools-generated scripts, especially in the configure itself around line 17342, where configure is desperately trying to figure out where boost libraries are. This was working in 1.1.11, but this is broken from 1.1.12 to 1.1.18 (most recent as of now). I was being able to build gearman on Solaris with boost 1.55-1.66 (any version) by patching the configure of the 1.1.18 like this:

adding "BOOSTLIBDIR=/usr/local/boost/lib" (mine boost was installed in custom prefix) after line "if test "x$ax_boost_user_program_options_lib" = "x"; then". But this is purely hackish way of dealing with it, so I think the autotools templates that the configure is generated from should be patched or reconsidered.

**Comment by carpii** [comment]
I had the same issue compiling 1.1.12 
boost-devel was installed but wasn't being detected, even when I pass --with-boost 

For whatever reason installing these packages allowed it to compile 

`
yum install gcc-c++.x86_64 gperf
`

**Comment by SpamapS** [comment]
Why would you be compiling 1.1.12? We're up to 1.1.18 now.

Quoting carpii (2019-02-02 12:14:06)

**Comment by carpii** [comment]
> Why would you be compiling 1.1.12? We're up to 1.1.18 now

It was really just because I was redeploying a legacy server in an emergency. 
I did try compiling 1.18 first, but had more problems then 1.12 (which is what dev server currently uses).

I'll be working on upgrading in the near future

**Comment by easterism** [comment]
I've got the same error for version 1.1.19 
Debian GNU/Linux 10 (buster)
```
checking for boostlib >= 1.39... configure: We could not detect the boost libraries (version 1.39 or higher)
```
at the same time
```
libboost-all-dev is already the newest version (1.67.0.1).
```

**Comment by esabol** [comment]
> I've got the same error for version 1.1.190
> Debian GNU/Linux 10 (buster)

Hello! This issue probably should've been closed previously. I would call this a new issue since CentOS 7 and Debian 10 are very different, but, hey, we're here now. :smile:

Unfortunately, I don't have a Dockerfile for building gearmand on Debian, so I don't have a solution ready. I don't have a Debian system readily available, and I don't have any real experience using Debian (everything is RHEL/CentOS with some Ubuntu where I work). We should probably add Debian to our CI workflow though.

Are you willing to help with debugging this? Maybe try compiling from the GitHub master branch source? The first thing I'd probably recommend trying is updating `m4/ax_boost_base.m4` to a newer version before generating the `configure` script.

**Comment by esabol** [comment]
Wait, are you actually compiling 1.1.19 and not 1.1.19.1? If so, you definitely want to download the 1.1.19.1 release source code. 1.1.19 wasn't packaged correctly for release and should be avoided.

The [Debian package description](http://deb.debian.org/debian/pool/main/g/gearmand/gearmand_1.1.19.1+ds-2.dsc) shows the following build dependencies:
```
Build-Depends: autoconf, automake, chrpath, debhelper-compat (= 10), default-libmysqlclient-dev, gperf, lcov, libboost-program-options-dev, libboost-system-dev, libboost-thread-dev, libcurl4-gnutls-dev, libevent-dev, libhiredis-dev, libltdl-dev, libmemcached-dev, libpq-dev, libsasl2-dev, libsqlite3-dev, libtool, memcached, pkg-config, procps, python3-sphinx, sharness, systemtap-sdt-dev [amd64 armel armhf i386 ia64 powerpc s390], uuid-dev
```
Not sure if that's for Debian 10 or not, but are you sure you have all of those installed? You'd think `libboost-all-dev` would cover everything, but maybe it doesn't....

Is there a reason why you want to compile from source instead of using the Debian package?

https://packages.debian.org/bullseye/gearman-job-server

**Comment by easterism** [comment]
@esabol I did it for master (1.1.19.1 for now) as well, same result. 
Btw, on another Debian 8 it run quite well...

> Is there a reason why you want to compile from source instead of using the Debian package?

no special reason, but i stuck with strange issue (like #343). Conditions: Debian package 1.1.18+ds single server at the same host, 3 workers, very rare usage. Suddenly php client wont connect. I checking `gearadmin --status` (every second)
- first sec. OK, list of workers, no queue
- next sec. OK, list of workers, no queue
- next sec. OK, list of workers, no queue
- next sec. OK, list of workers, no queue
- next sec. STUCK, no output untill Ctrl+C

I've no idea why it happens but reinstall gearman-job-server temporarly help. Next 1-2 day it works well, but next sh... happens again.

So I hope compile from source will help... but I've no success yet

P.S. Its all about production server. On my dev server with completly same condition it works well. So looks like its a kind of magic :)

**Comment by esabol** [comment]
> I did it for master (1.1.19.1 for now) as well, same result.
> Btw, on another Debian 8 it run quite well...

Well, you didn't answer my question in my previous post:

>> The [Debian package description](http://deb.debian.org/debian/pool/main/g/gearmand/gearmand_1.1.19.1+ds-2.dsc) lists the following build dependencies:
```
Build-Depends: autoconf, automake, chrpath, debhelper-compat (= 10),
 default-libmysqlclient-dev, gperf, lcov, libboost-program-options-dev,
 libboost-system-dev, libboost-thread-dev, libcurl4-gnutls-dev, libevent-dev,
 libhiredis-dev, libltdl-dev, libmemcached-dev, libpq-dev, libsasl2-dev,
 libsqlite3-dev, libtool, memcached, pkg-config, procps, python3-sphinx,
 sharness, systemtap-sdt-dev [amd64 armel armhf i386 ia64 powerpc s390],
 uuid-dev
```
>> Not sure if that's for Debian 10 or not, but are you sure you have all of those (packages) installed?

Answering that question is step 1.

**Comment by easterism** [comment]
> You'd think libboost-all-dev would cover everything, but maybe it doesn't...

Right, it doesn't! 

`apt install autoconf  automake  chrpath  debhelper-compat` help me run .configure correctly

`apt install python3-sphinx` help to `make`.

I supose it should be added to the Debian package.

@esabol thank you again!
