### ISSUE TITLE
Does 'WORK_EXCEPTION' work for now?

### ISSUE THREAD

**Issue by mike442144** [gearman/gearmand#70]
Hi, I notice that https://bugs.launchpad.net/gearmand/+bug/405732 said the 'work_exception' did not behavior like the protocol description.

```
WORK_EXCEPTION

    This is to notify the server (and any listening clients) that 
    the job failed with the given exception.

    Arguments:
    - NULL byte terminated job handle.
    - Opaque data that is returned to the client as an exception.

```

I want client to know the error detail for a failed job. But 'WORK_FAIL' cannot carry the information, do you have any idea? thanks.

**Comment by p-alik** [comment]
LP ticket points to the [patch](https://github.com/xing/gearman-server/commit/8ae1ee84a1e812dd5f6f526ec22e322c9ded4438). We'll see if it solve the issue.

**Comment by p-alik** [comment]
@mike442144 there is indeed a bug in gearmand implementation because the daemon crashes if worker sends `WORK_EXCEPTION` request.

As recommended [here](https://bugs.launchpad.net/gearmand/+bug/405732/comments/1) you could use `WORK_WARNING` instead of `WORK_EXCEPTION`.
`WORK_WARNING` works fine in tests on 6d8717847a01af85e308cf45babfde1ce4cb4f4b .

**Comment by p-alik** [comment]
> LP ticket points to the [patch](https://github.com/xing/gearman-server/commit/8ae1ee84a1e812dd5f6f526ec22e322c9ded4438). We'll see if it solve the issue.

The patch is for gearmand v0.9 and it was not applied for a good reason:
"[This is actually not a bug, this is the desired behavior](https://bugs.launchpad.net/gearmand/+bug/405732/comments/1)"

**Comment by mike442144** [comment]
Okay, thanks.

**Comment by SpamapS** [comment]
Looks like this was not realy a bug, just like the referenced LP bug.
