### ISSUE TITLE
gearadmin shows wrong queue size

### ISSUE THREAD

**Issue by accountstam** [gearman/gearmand#79]
steps to reproduce:

1. start gearmand on server1
2. start a gearman worker on server2 that registers a function
3. unplug or remove power from server2
4. run gearadmin --status

the queue length of that function will still show a registered worker even though there are none

The original bug is here: https://bugs.launchpad.net/gearmand/+bug/1498677

**Comment by SpamapS** [comment]
I'm not sure this is a bug. There's no "liveness" guaranteed in the gearman protocol itself. The worker's absence will eventually be detected by gearman if either:

1.  The worker is sent a NOOP to wake it up, at which point normal TCP unacknowledged packet semantics begin and a timeout will happen (system configured)
2.  gearmand is passed --keepalive, at which point the system level TCP keepalive interval will determine how long it takes to detect a missing worker. There is also --keepalive-idle, --keepalive-interval, and --keepalive-count, that help tune this for faster keepalive kills, as these have relatively conservative defaults in most operating system. These options are fully documented in doc/source/gearmand.rst

So, I'm not sure what more we would do to fix this. Given that, I'm going to close it (and the LP bug). Please do feel free to re-open or open a new one referring to this if you disagree or have more data to provide. Thanks for taking the time to open the issue!
