### ISSUE TITLE
Unique key queue 

### ISSUE THREAD

**Issue by sirgalleto** [gearman/gearmand#80]
Hi, I'm testing your queue feature for an integration with my system but I have errors persisting the data with the diferent databases connection. 

1. Redis: The queue try to insert the diferent jobs with the same key and at the end you only have one job persisted.
2. MySQL: The queue try to insert the job details with the same uniq quey as this log says: `  ERROR 2017-03-01 00:52:07.000000 [  proc ] mysql_stmt_execute failed: Duplicate entry 'sb_reverse' for key 'unique_key' -> libgearman-server/plugins/queue/mysql/queue.cc:357`. 

Am i ignoring any configuration before start my queue or is a bug? How can I run successfully the queue feature? 

OS: MacOS Sierra
Gearman version: 1.1.15

Thanks!

**Comment by p-alik** [comment]
@sirgalleto,
I guess you use same key for various tasks. If you add a job without unique key `gearmand`  will be worried about uniqueness of the jobs.

For instance:
```bash
$ gearman -f foo -h localhost -p 4730 -s -b
$ gearman -f foo -h localhost -p 4730 -s -b
```
produce two entries in Redis: 
```bash
127.0.0.1:6379> keys *
1) "_gear_-foo-9c371e8a-fe9c-11e6-8572-7446a09167b1"
2) "_gear_-foo-988912d4-fe9c-11e6-8572-7446a09167b1"
```
but with - not realy - unique key: 
```bash
$ gearman -f foo -h localhost -p 4730 -s -b -u xyz
$ gearman -f foo -h localhost -p 4730 -s -b -u xyz
```
you'll get only one entry in Redis:
```bash
1) "_gear_-foo-xyz
```

**Comment by p-alik** [comment]
@sirgalleto, don't hesitate to reopen the issue if you'll get trouble with this regard

**Comment by p-alik** [comment]
@sirgalleto, if you installed your `gearmand` from sources, please, share your add your experiences  to the issue #73

**Comment by sirgalleto** [comment]
@p-alik I ignored the unique id process, your answer was very helpful. Thanks. 

+1 dev point 😛

**Comment by p-alik** [comment]
you are welcome!
