### ISSUE TITLE
unique_size assertion kills gearmand start

### ISSUE THREAD

**Issue by p-alik** [gearman/gearmand#87]
steps to reproduce
- start `gearmand` with memcache queue
  ```bash
v1.1.15/sbin/gearmand --verbose DEBUG -p 4731 --queue-type libmemcached --libmemcached-servers 127.0.0.1:11211
```
- add some jobs without unique key
- stop `gearmand`
- start `gearmand` ends in exception: 
```text
/home/apastuchov/v1.1.15/sbin/gearmand: Could not open log file "/home/apastuchov/v1.1.15/var/log/gearmand.log", from "/home/apastuchov", switching to stderr. (No such file or directory)
  DEBUG 2017-03-21 10:37:44.094472 [  main ] THREADS: 4 -> libgearman-server/gearmand.cc:263
   INFO 2017-03-21 10:37:44.094718 [  main ] Initializing libmemcached module
   INFO 2017-03-21 10:37:44.095136 [  main ] Initializing Gear on port 4731 with SSL: false
   INFO 2017-03-21 10:37:44.095318 [  main ] Starting up with pid 17081, verbose is set to DEBUG
  DEBUG 2017-03-21 10:37:44.095657 [  main ] Method for libevent: epoll -> libgearman-server/gearmand.cc:364
  DEBUG 2017-03-21 10:37:44.095985 [  main ] Trying to listen on 0.0.0.0:4731 -> libgearman-server/gearmand.cc:646
   INFO 2017-03-21 10:37:44.096246 [  main ] Listening on 0.0.0.0:4731 (9)
  DEBUG 2017-03-21 10:37:44.096421 [  main ] Trying to listen on :::4731 -> libgearman-server/gearmand.cc:646
   INFO 2017-03-21 10:37:44.096591 [  main ] Listening on :::4731 (10)
  DEBUG 2017-03-21 10:37:44.096843 [  main ] Creating wakeup pipe -> libgearman-server/gearmand.cc:915
  DEBUG 2017-03-21 10:37:44.097017 [  main ] Creating 4 threads -> libgearman-server/gearmand.cc:378
  DEBUG 2017-03-21 10:37:44.097244 [  main ] Initializing libevent for IO thread -> libgearman-server/gearmand_thread.cc:224
  DEBUG 2017-03-21 10:37:44.097476 [  main ] Creating IO thread wakeup pipe -> libgearman-server/gearmand_thread.cc:495
  DEBUG 2017-03-21 10:37:44.097699 [  main ] Thread 1 created -> libgearman-server/gearmand_thread.cc:273
  DEBUG 2017-03-21 10:37:44.097969 [  main ] Initializing libevent for IO thread -> libgearman-server/gearmand_thread.cc:224
  DEBUG 2017-03-21 10:37:44.098221 [  main ] Creating IO thread wakeup pipe -> libgearman-server/gearmand_thread.cc:495
  DEBUG 2017-03-21 10:37:44.098467 [  main ] Thread 2 created -> libgearman-server/gearmand_thread.cc:273
  DEBUG 2017-03-21 10:37:44.098699 [  main ] Initializing libevent for IO thread -> libgearman-server/gearmand_thread.cc:224
  DEBUG 2017-03-21 10:37:44.098979 [  main ] Creating IO thread wakeup pipe -> libgearman-server/gearmand_thread.cc:495
  DEBUG 2017-03-21 10:37:44.099232 [  main ] Thread 3 created -> libgearman-server/gearmand_thread.cc:273
  DEBUG 2017-03-21 10:37:44.099468 [  main ] Initializing libevent for IO thread -> libgearman-server/gearmand_thread.cc:224
  DEBUG 2017-03-21 10:37:44.099707 [  main ] Creating IO thread wakeup pipe -> libgearman-server/gearmand_thread.cc:495
  DEBUG 2017-03-21 10:37:44.099981 [  main ] Thread 4 created -> libgearman-server/gearmand_thread.cc:273
  DEBUG 2017-03-21 10:37:44.100386 [  main ] replaying queue: begin -> libgearman-server/gearmand.cc:391
  DEBUG 2017-03-21 10:37:44.100585 [  main ] libmemcached replay start -> libgearman-server/plugins/queue/libmemcached/queue.cc:375
  DEBUG 2017-03-21 10:37:44.101303 [  main ] SUCCESS -> libgearman-server/plugins/queue/libmemcached/queue.cc:357
  DEBUG 2017-03-21 10:37:44.101583 [  main ] SUCCESS -> libgearman-server/plugins/queue/libmemcached/queue.cc:357
  DEBUG 2017-03-21 10:37:44.101819 [  main ] unique: '(null)', size: '-945361264' -> libgearman-server/plugins/queue/libmemcached/queue.cc:314
gearmand: libgearman-server/plugins/queue/libmemcached/queue.cc:316: callback_loader: Assertion `unique_size' failed.
```

[LP PR](http://bazaar.launchpad.net/~1-infe-w/gearmand/1.0/revision/806) for the issue was already declined. Any other suggestion to solve the issue?

**Comment by SpamapS** [comment]
Can we just deprecate and remove the libmemcached queue? At least the others have a point. This is just moving things from one non-persistent in-memory store to another.

**Comment by p-alik** [comment]
In my company we are using patched memcache persistence for near two years. I'm working on this issue.

**Comment by SpamapS** [comment]
Thanks for working it @p-alik . I had no idea somebody had come up with a serious use case for the libmemcached queue backend. It was originally just kind of a throw-away "look what we can do" thing.

**Comment by p-alik** [comment]
I compared the behavior of  [libmemcached](https://github.com/gearman/gearmand/blob/master/libgearman-server/plugins/queue/libmemcached/queue.cc#L289) and [redis](https://github.com/gearman/gearmand/blob/master/libgearman-server/plugins/queue/redis/queue.cc#L71) queue plugins. Except first one crashes on `assert(unique_size)` it's the same. An unique key is not mandatory for a job and the is no use of asserting optional job property.

On the other side putting _background_ jobs without unique key into the queue is really bad idea, because after `gearmand` restart the only last one will be restored. For instance `gearman` cli [adds](https://github.com/gearman/gearmand/blob/master/libgearman/add.cc#L227) an unique key for background jobs on default.

Conclusion: We have to remove both [unique assertions](https://github.com/gearman/gearmand/blob/master/libgearman-server/plugins/queue/libmemcached/queue.cc#L317) and add a note about importance of unique key for background jobs into [protocol](http://gearman.org/protocol/)

Any objection?

**Comment by SpamapS** [comment]
Great analysis, thanks!

`assert()` does in fact seem like the wrong way to go about this. I think the right behaviour is to accept a 0 length string as a unique ID, and just update the protocol doc. I wouldn't mind adding a mode of "ERROR on empty unique ID" but that sounds like a new feature, and this is definitely just a bug.
