### ISSUE TITLE
libmemcached discovery can't be disabled in configure

### ISSUE THREAD

**Issue by sevein** [gearman/gearmand#92]
I've tried passing `--disable-libmemcached` to `configure` but I still see it's trying to reach it and the report warns the libraries were not found. Thank you in advance!

**Comment by SpamapS** [comment]
This is just a quirk of m4/ax_libmemcached.m4. The disable flag just disables the build flags after discovery. I tested and if the library is installed, but --disable-libmemcached is passed, we still don't build with libmemcached support. Is the discovery part causing you pain, or just trying to streamline the build?

**Comment by p-alik** [comment]
@sevein, could you provide more information please because in my environment I can't reproduce the issue.
I tested `./configure --disable-libmemcached`
- without `libmemcached-dev`: build + `make test` OK
```text
   * CPP Flags:                  -fvisibility=hidden
   * LIBS:                      
   * LDFLAGS Flags:              -Werror -rdynamic
   * Assertions enabled:        yes
   * Debug enabled:             no
   * Warnings as failure:       yes
   * Building with libsqlite3   yes
   * Building with libdrizzle   yes
   * Building with libmemcached not found
   * Building with libpq        no
   * Building with tokyocabinet no
   * Building with libmysql     yes
   * SSL enabled:               no
   * cyassl found:              no
   * openssl found:             yes
   * make -j:                   5
   * VCS checkout:              yes
   * sphinx-build:              /usr/bin/sphinx-build
```

-  with `libmemcached-dev`: build and `make test` OK
```text
* CPP Flags:                  -fvisibility=hidden
   * LIBS:                      
   * LDFLAGS Flags:              -Werror -rdynamic
   * Assertions enabled:        yes
   * Debug enabled:             no
   * Warnings as failure:       yes
   * Building with libsqlite3   yes
   * Building with libdrizzle   yes
   * Building with libmemcached no
   * Building with libpq        no
   * Building with tokyocabinet no
   * Building with libmysql     yes
   * SSL enabled:               no
   * cyassl found:              no
   * openssl found:             yes
   * make -j:                   5
   * VCS checkout:              yes
   * sphinx-build:              /usr/bin/sphinx-build
```

**Comment by sevein** [comment]
> * Building with libmemcached not found

@p-alik, ^ was the confusing part. You used the disable flag but it was still reported as not found. Thanks for clarifying that, @SpamapS.

> Is the discovery part causing you pain, or just trying to streamline the build?

Originally, I was trying to troubleshoot why the gearmand package provided by Alpine Linux wasn't including support for the libmemcached backend even though `libmemcached-dev` was being installed (see [APKBUILD](http://git.alpinelinux.org/cgit/aports/tree/testing/gearmand/APKBUILD#n11) for more details). I filed a [ticket](https://bugs.alpinelinux.org/issues/7065) in their repo. I ran into this comment you wrote a while ago: https://github.com/gearman/gearmand/issues/26#issuecomment-254959557 and I realized that their [libmemcached-dev package](http://git.alpinelinux.org/cgit/aports/tree/main/libmemcached/APKBUILD?h=3.4-stable#n35) is compiled using the `--disable-static` and it does not install `libmemcached.a`. Is that perhaps the problem?

This is probably unrelated by my ultimate goal is to build a lightweight Docker image of your latest release of gearmand based on Alpine Linux supporting `builtin`, `libmemcached` and `redis`. I've found more than 100 images in hub.docker.com but they quite not fit my idea of lightweight or they're outdated. My current attempt takes only 18.5 MB: https://hub.docker.com/r/artefactual/docker-gearmand. It'd be cool to eventually submit this to the "Official Images" program under github.com/docker-library.

**Comment by SpamapS** [comment]
Yes, if you don't have libmemcached.a you can't link things.

Is there still something we need to fix/change in gearmand?

**Comment by sevein** [comment]
Thank you so much!
