### ISSUE TITLE
What should I configure in order to use the HTTP plugin

### ISSUE THREAD

**Issue by silviucpp** [gearman/gearmand#96]
Hello,

I'm trying to use the HTTP interface but seems gearman is not listening on the port I specify. Also In logs
I cannot find any error or anything regarding HTTP.

I'm using the following command:

sudo gearmand --http-port=5555 --verbose=INFO --syslog

But nothing listen on that port

Thanks,
Silviu

**Comment by p-alik** [comment]
you have to add `--protocol=http` parameter:

If strongly recommend you to use `POST` requests. Do not use `GET` because the gearmand `HTTP` implementation handles it badly yet. 
1. `gearmand --protocol=http --http-port=8081`
1. submit a job
`$ curl -XPOST http://localhost:8081/foo -d 'bar'`
1. run a worker:
```
$ gearman -c1 -w -f foo -s
bar
```

**Comment by p-alik** [comment]
Do not hesitate to reopen the issue if you need.

**Comment by silviucpp** [comment]
Thanks I'll try this. !

I think at least documentation should be updated . I can't find anywhere the setting you provided :)

Silviu

**Comment by p-alik** [comment]
`--protocol=http` is mentioned in the top of [Job Server Options](http://gearman.org/manual/job_server/#extended_protocols) but you are absolutely right documentation should be updated.

**Comment by silviucpp** [comment]
Hmm still I have issues with background jobs:

curl --request POST --url http://127.0.0.1:8081/silviu --header 'X-Gearman-Background:true' --data 'Hello world!'

My client is not getting any response back and neither curl. I also see the job in the gearman server. But somehow is not considered a background job.. And I think server waits to be processed in order to send back the response

Silviu

**Comment by silviucpp** [comment]
Based on logs seems job is marked as background one.. but still no response to client

**Comment by silviucpp** [comment]
Looking to the code for me this seems a bug. In case of a background job when you don't have any consumer registered yet the only message generated is GEARMAN_COMMAND_JOB_CREATED but for this message no response is sent back.

**Comment by p-alik** [comment]
@silviucpp, indeed it's a bug. Thank you for reporting.
I put it in #98
